// swift-tools-version:6.0
// The Sky Bother engine (scoring, planning, ephemeris) built from the Mac app's
// own source files, symlinked under Sources/SkyBotherEngine/Shared, so the Mac
// and web apps give identical results. Built for WebAssembly by web/build-engine.sh.
import PackageDescription

let package = Package(
    name: "SkyBotherEngine",
    platforms: [.macOS(.v14)],
    targets: [
        .target(name: "SkyBotherEngine", swiftSettings: [.swiftLanguageMode(.v5)]),
        // Native twin of engine.wasm, for the parity check (web/scripts/parity.mjs).
        .executableTarget(name: "engine-cli", dependencies: ["SkyBotherEngine"]),
        .executableTarget(name: "engine-wasm", dependencies: ["SkyBotherEngine", "ICUDataSlim"],
                          linkerSettings: [.unsafeFlags(["-Xclang-linker", "-mexec-model=reactor"])]),
        // ICU's data cut down to what the engine uses (34 MB → under 2 MB); its
        // `icudt76_dat` is linked before lib_FoundationICU.a, so the SDK's copy
        // is never pulled in. The C file is generated by build-engine.sh.
        .target(name: "ICUDataSlim"),
    ]
)
