import Foundation

extension BuiltInCatalog {
    /// The brightest named stars, and the doubles and red stars that suit a
    /// small scope. Positions and V magnitudes are from SIMBAD (J2000);
    /// Alpha Centauri, Acrux, Mizar and Epsilon Lyrae carry the combined
    /// light of the pair.
    ///
    /// A single star's size is nominal — it is a point. A double's is the
    /// separation of its pair, which is what decides whether a rig splits it.
    static let stars: [Target] = [
        Target(designation: "α CMa", commonName: "Sirius", type: .star,
               rightAscension: 101.2872, declination: -16.7161, magnitude: -1.46,
               majorAxisArcminutes: 0.1, minorAxisArcminutes: 0.1, constellation: "CMa"),
        Target(designation: "α Car", commonName: "Canopus", type: .star,
               rightAscension: 95.9880, declination: -52.6957, magnitude: -0.74,
               majorAxisArcminutes: 0.1, minorAxisArcminutes: 0.1, constellation: "Car"),
        Target(designation: "α Cen", commonName: "Rigil Kentaurus", type: .star,
               rightAscension: 219.9021, declination: -60.8340, magnitude: -0.27,
               majorAxisArcminutes: 0.1, minorAxisArcminutes: 0.1, constellation: "Cen"),
        Target(designation: "α Boo", commonName: "Arcturus", type: .star,
               rightAscension: 213.9153, declination: +19.1824, magnitude: -0.05,
               majorAxisArcminutes: 0.1, minorAxisArcminutes: 0.1, constellation: "Boo"),
        Target(designation: "α Lyr", commonName: "Vega", type: .star,
               rightAscension: 279.2347, declination: +38.7837, magnitude: 0.03,
               majorAxisArcminutes: 0.1, minorAxisArcminutes: 0.1, constellation: "Lyr"),
        Target(designation: "α Aur", commonName: "Capella", type: .star,
               rightAscension: 79.1723, declination: +45.9980, magnitude: 0.08,
               majorAxisArcminutes: 0.1, minorAxisArcminutes: 0.1, constellation: "Aur"),
        Target(designation: "β Ori", commonName: "Rigel", type: .star,
               rightAscension: 78.6345, declination: -8.2016, magnitude: 0.13,
               majorAxisArcminutes: 0.1, minorAxisArcminutes: 0.1, constellation: "Ori"),
        Target(designation: "α CMi", commonName: "Procyon", type: .star,
               rightAscension: 114.8255, declination: +5.2250, magnitude: 0.37,
               majorAxisArcminutes: 0.1, minorAxisArcminutes: 0.1, constellation: "CMi"),
        Target(designation: "α Eri", commonName: "Achernar", type: .star,
               rightAscension: 24.4285, declination: -57.2368, magnitude: 0.46,
               majorAxisArcminutes: 0.1, minorAxisArcminutes: 0.1, constellation: "Eri"),
        Target(designation: "α Ori", commonName: "Betelgeuse", type: .star,
               rightAscension: 88.7929, declination: +7.4071, magnitude: 0.42,
               majorAxisArcminutes: 0.1, minorAxisArcminutes: 0.1, constellation: "Ori"),
        Target(designation: "β Cen", commonName: "Hadar", type: .star,
               rightAscension: 210.9559, declination: -60.3730, magnitude: 0.58,
               majorAxisArcminutes: 0.1, minorAxisArcminutes: 0.1, constellation: "Cen"),
        Target(designation: "α Aql", commonName: "Altair", type: .star,
               rightAscension: 297.6958, declination: +8.8683, magnitude: 0.76,
               majorAxisArcminutes: 0.1, minorAxisArcminutes: 0.1, constellation: "Aql"),
        Target(designation: "α Cru", commonName: "Acrux", type: .star,
               rightAscension: 186.6496, declination: -63.0991, magnitude: 0.76,
               majorAxisArcminutes: 0.1, minorAxisArcminutes: 0.1, constellation: "Cru"),
        Target(designation: "α Tau", commonName: "Aldebaran", type: .star,
               rightAscension: 68.9802, declination: +16.5093, magnitude: 0.86,
               majorAxisArcminutes: 0.1, minorAxisArcminutes: 0.1, constellation: "Tau"),
        Target(designation: "α Sco", commonName: "Antares", type: .star,
               rightAscension: 247.3519, declination: -26.4320, magnitude: 0.91,
               majorAxisArcminutes: 0.1, minorAxisArcminutes: 0.1, constellation: "Sco"),
        Target(designation: "α Vir", commonName: "Spica", type: .star,
               rightAscension: 201.2982, declination: -11.1613, magnitude: 0.97,
               majorAxisArcminutes: 0.1, minorAxisArcminutes: 0.1, constellation: "Vir"),
        Target(designation: "β Gem", commonName: "Pollux", type: .star,
               rightAscension: 116.3290, declination: +28.0262, magnitude: 1.14,
               majorAxisArcminutes: 0.1, minorAxisArcminutes: 0.1, constellation: "Gem"),
        Target(designation: "α PsA", commonName: "Fomalhaut", type: .star,
               rightAscension: 344.4127, declination: -29.6222, magnitude: 1.16,
               majorAxisArcminutes: 0.1, minorAxisArcminutes: 0.1, constellation: "PsA"),
        Target(designation: "α Cyg", commonName: "Deneb", type: .star,
               rightAscension: 310.3580, declination: +45.2803, magnitude: 1.25,
               majorAxisArcminutes: 0.1, minorAxisArcminutes: 0.1, constellation: "Cyg"),
        Target(designation: "β Cru", commonName: "Mimosa", type: .star,
               rightAscension: 191.9303, declination: -59.6888, magnitude: 1.25,
               majorAxisArcminutes: 0.1, minorAxisArcminutes: 0.1, constellation: "Cru"),
        Target(designation: "α Leo", commonName: "Regulus", type: .star,
               rightAscension: 152.0930, declination: +11.9672, magnitude: 1.40,
               majorAxisArcminutes: 0.1, minorAxisArcminutes: 0.1, constellation: "Leo"),
        Target(designation: "ε CMa", commonName: "Adhara", type: .star,
               rightAscension: 104.6565, declination: -28.9721, magnitude: 1.50,
               majorAxisArcminutes: 0.1, minorAxisArcminutes: 0.1, constellation: "CMa"),
        Target(designation: "α Gem", commonName: "Castor", type: .star,
               rightAscension: 113.6495, declination: +31.8883, magnitude: 1.58,
               majorAxisArcminutes: 0.1, minorAxisArcminutes: 0.1, constellation: "Gem"),
        Target(designation: "γ Ori", commonName: "Bellatrix", type: .star,
               rightAscension: 81.2828, declination: +6.3497, magnitude: 1.64,
               majorAxisArcminutes: 0.1, minorAxisArcminutes: 0.1, constellation: "Ori"),
        Target(designation: "β Tau", commonName: "Elnath", type: .star,
               rightAscension: 81.5730, declination: +28.6075, magnitude: 1.65,
               majorAxisArcminutes: 0.1, minorAxisArcminutes: 0.1, constellation: "Tau"),
        Target(designation: "ε Ori", commonName: "Alnilam", type: .star,
               rightAscension: 84.0534, declination: -1.2019, magnitude: 1.69,
               majorAxisArcminutes: 0.1, minorAxisArcminutes: 0.1, constellation: "Ori"),
        Target(designation: "ζ Ori", commonName: "Alnitak", type: .star,
               rightAscension: 85.1897, declination: -1.9426, magnitude: 1.77,
               majorAxisArcminutes: 0.1, minorAxisArcminutes: 0.1, constellation: "Ori"),
        Target(designation: "δ Ori", commonName: "Mintaka", type: .star,
               rightAscension: 83.0017, declination: -0.2991, magnitude: 2.41,
               majorAxisArcminutes: 0.1, minorAxisArcminutes: 0.1, constellation: "Ori"),
        Target(designation: "ε UMa", commonName: "Alioth", type: .star,
               rightAscension: 193.5073, declination: +55.9598, magnitude: 1.77,
               majorAxisArcminutes: 0.1, minorAxisArcminutes: 0.1, constellation: "UMa"),
        Target(designation: "α UMa", commonName: "Dubhe", type: .star,
               rightAscension: 165.9320, declination: +61.7510, magnitude: 1.79,
               majorAxisArcminutes: 0.1, minorAxisArcminutes: 0.1, constellation: "UMa"),
        Target(designation: "α Per", commonName: "Mirfak", type: .star,
               rightAscension: 51.0807, declination: +49.8612, magnitude: 1.79,
               majorAxisArcminutes: 0.1, minorAxisArcminutes: 0.1, constellation: "Per"),
        Target(designation: "η UMa", commonName: "Alkaid", type: .star,
               rightAscension: 206.8852, declination: +49.3133, magnitude: 1.86,
               majorAxisArcminutes: 0.1, minorAxisArcminutes: 0.1, constellation: "UMa"),
        Target(designation: "ε Sgr", commonName: "Kaus Australis", type: .star,
               rightAscension: 276.0430, declination: -34.3846, magnitude: 1.81,
               majorAxisArcminutes: 0.1, minorAxisArcminutes: 0.1, constellation: "Sgr"),
        Target(designation: "α Gru", commonName: "Alnair", type: .star,
               rightAscension: 332.0583, declination: -46.9610, magnitude: 1.71,
               majorAxisArcminutes: 0.1, minorAxisArcminutes: 0.1, constellation: "Gru"),
        Target(designation: "α UMi", commonName: "Polaris", type: .star,
               rightAscension: 37.9546, declination: +89.2641, magnitude: 2.02,
               majorAxisArcminutes: 0.1, minorAxisArcminutes: 0.1, constellation: "UMi"),
        Target(designation: "α And", commonName: "Alpheratz", type: .star,
               rightAscension: 2.0969, declination: +29.0904, magnitude: 2.06,
               majorAxisArcminutes: 0.1, minorAxisArcminutes: 0.1, constellation: "And"),
        Target(designation: "α Ari", commonName: "Hamal", type: .star,
               rightAscension: 31.7934, declination: +23.4624, magnitude: 2.01,
               majorAxisArcminutes: 0.1, minorAxisArcminutes: 0.1, constellation: "Ari"),
        Target(designation: "β Per", commonName: "Algol", type: .star,
               rightAscension: 47.0422, declination: +40.9556, magnitude: 2.12,
               majorAxisArcminutes: 0.1, minorAxisArcminutes: 0.1, constellation: "Per"),
        Target(designation: "α Oph", commonName: "Rasalhague", type: .star,
               rightAscension: 263.7336, declination: +12.5600, magnitude: 2.07,
               majorAxisArcminutes: 0.1, minorAxisArcminutes: 0.1, constellation: "Oph"),
        Target(designation: "σ Sgr", commonName: "Nunki", type: .star,
               rightAscension: 283.8164, declination: -26.2967, magnitude: 2.07,
               majorAxisArcminutes: 0.1, minorAxisArcminutes: 0.1, constellation: "Sgr"),
        Target(designation: "β UMi", commonName: "Kochab", type: .star,
               rightAscension: 222.6764, declination: +74.1555, magnitude: 2.08,
               majorAxisArcminutes: 0.1, minorAxisArcminutes: 0.1, constellation: "UMi"),
        Target(designation: "ε Peg", commonName: "Enif", type: .star,
               rightAscension: 326.0465, declination: +9.8750, magnitude: 2.39,
               majorAxisArcminutes: 0.1, minorAxisArcminutes: 0.1, constellation: "Peg"),
        Target(designation: "β Cet", commonName: "Diphda", type: .star,
               rightAscension: 10.8974, declination: -17.9866, magnitude: 2.01,
               majorAxisArcminutes: 0.1, minorAxisArcminutes: 0.1, constellation: "Cet"),
        Target(designation: "α Peg", commonName: "Markab", type: .star,
               rightAscension: 346.1902, declination: +15.2053, magnitude: 2.48,
               majorAxisArcminutes: 0.1, minorAxisArcminutes: 0.1, constellation: "Peg"),
        Target(designation: "γ Cyg", commonName: "Sadr", type: .star,
               rightAscension: 305.5571, declination: +40.2567, magnitude: 2.23,
               majorAxisArcminutes: 0.1, minorAxisArcminutes: 0.1, constellation: "Cyg"),
        Target(designation: "β Leo", commonName: "Denebola", type: .star,
               rightAscension: 177.2649, declination: +14.5721, magnitude: 2.13,
               majorAxisArcminutes: 0.1, minorAxisArcminutes: 0.1, constellation: "Leo"),
        Target(designation: "λ Sco", commonName: "Shaula", type: .star,
               rightAscension: 263.4022, declination: -37.1038, magnitude: 1.63,
               majorAxisArcminutes: 0.1, minorAxisArcminutes: 0.1, constellation: "Sco"),
        Target(designation: "ζ UMa", commonName: "Mizar and Alcor", type: .star,
               rightAscension: 200.9814, declination: +54.9254, magnitude: 2.23,
               majorAxisArcminutes: 11.8, minorAxisArcminutes: 11.8, constellation: "UMa"),
        Target(designation: "β Cyg", commonName: "Albireo", type: .star,
               rightAscension: 292.6803, declination: +27.9597, magnitude: 3.08,
               majorAxisArcminutes: 0.573, minorAxisArcminutes: 0.573, constellation: "Cyg"),
        Target(designation: "γ And", commonName: "Almach", type: .star,
               rightAscension: 30.9748, declination: +42.3297, magnitude: 2.10,
               majorAxisArcminutes: 0.16, minorAxisArcminutes: 0.16, constellation: "And"),
        Target(designation: "ε Lyr", commonName: "Double Double", type: .star,
               rightAscension: 281.0848, declination: +39.6701, magnitude: 4.70,
               majorAxisArcminutes: 3.47, minorAxisArcminutes: 3.47, constellation: "Lyr"),
        Target(designation: "μ Cep", commonName: "Garnet Star", type: .star,
               rightAscension: 325.8769, declination: +58.7800, magnitude: 4.08,
               majorAxisArcminutes: 0.1, minorAxisArcminutes: 0.1, constellation: "Cep"),
        Target(designation: "α CVn", commonName: "Cor Caroli", type: .star,
               rightAscension: 194.0069, declination: +38.3184, magnitude: 2.88,
               majorAxisArcminutes: 0.322, minorAxisArcminutes: 0.322, constellation: "CVn"),
        Target(designation: "η Cas", commonName: "Achird", type: .star,
               rightAscension: 12.2762, declination: +57.8152, magnitude: 3.44,
               majorAxisArcminutes: 0.223, minorAxisArcminutes: 0.223, constellation: "Cas"),
        Target(designation: "γ Del", commonName: "Gamma Delphini", type: .star,
               rightAscension: 311.6646, declination: +16.1243, magnitude: 4.25,
               majorAxisArcminutes: 0.152, minorAxisArcminutes: 0.152, constellation: "Del"),
        Target(designation: "Y CVn", commonName: "La Superba", type: .star,
               rightAscension: 191.2826, declination: +45.4403, magnitude: 4.87,
               majorAxisArcminutes: 0.1, minorAxisArcminutes: 0.1, constellation: "CVn"),
        Target(designation: "61 Cyg", commonName: "61 Cygni", type: .star,
               rightAscension: 316.7247, declination: +38.7494, magnitude: 5.21,
               majorAxisArcminutes: 0.527, minorAxisArcminutes: 0.527, constellation: "Cyg"),
        Target(designation: "ι Cnc", commonName: "Iota Cancri", type: .star,
               rightAscension: 131.6743, declination: +28.7599, magnitude: 4.02,
               majorAxisArcminutes: 0.508, minorAxisArcminutes: 0.508, constellation: "Cnc"),
    ]

    /// Red stars worth a look for their colour alone, beside the doubles.
    static let colouredStars: Set<String> = ["μ Cep", "Y CVn"]

    /// Named on the sky dome to find your way by: the first-magnitude stars
    /// and Polaris.
    static let signpostStars: [Target] = stars.filter { $0.magnitude < 1.6 || $0.designation == "α UMi" }
}

extension Target {
    /// A double, or a star with striking colour: something to show off in
    /// a picture, where a single white star is a point of light.
    var isShowpieceStar: Bool {
        type.isStar && (majorAxisArcminutes > 0.1 || BuiltInCatalog.colouredStars.contains(designation))
    }
}
