import Foundation

/// The built-in target list: the complete Messier catalogue plus the non-Messier
/// showpieces that people actually image. Positions are J2000 and are quoted to
/// about an arcminute, which is far finer than anything this app decides with.
/// Sizes are the visual extents commonly listed; for framing purposes the bright
/// core of a nebula is often smaller than its full catalogued extent.
enum BuiltInCatalog {

    static let messier: [Target] = [
        Target(designation: "M1", commonName: "Crab Nebula", type: .supernovaRemnant,
               rightAscension: 83.6250, declination: +22.0167, magnitude: 8.4,
               majorAxisArcminutes: 6, minorAxisArcminutes: 4, constellation: "Tau"),
        Target(designation: "M2", commonName: nil, type: .globularCluster,
               rightAscension: 323.3750, declination: -0.8167, magnitude: 6.5,
               majorAxisArcminutes: 16, minorAxisArcminutes: 16, constellation: "Aqr"),
        Target(designation: "M3", commonName: nil, type: .globularCluster,
               rightAscension: 205.5500, declination: +28.3833, magnitude: 6.2,
               majorAxisArcminutes: 18, minorAxisArcminutes: 18, constellation: "CVn"),
        Target(designation: "M4", commonName: nil, type: .globularCluster,
               rightAscension: 245.9000, declination: -26.5333, magnitude: 5.6,
               majorAxisArcminutes: 26, minorAxisArcminutes: 26, constellation: "Sco"),
        Target(designation: "M5", commonName: nil, type: .globularCluster,
               rightAscension: 229.6500, declination: +2.0833, magnitude: 5.6,
               majorAxisArcminutes: 23, minorAxisArcminutes: 23, constellation: "Ser"),
        Target(designation: "M6", commonName: "Butterfly Cluster", type: .openCluster,
               rightAscension: 265.0250, declination: -32.2167, magnitude: 4.2,
               majorAxisArcminutes: 25, minorAxisArcminutes: 25, constellation: "Sco"),
        Target(designation: "M7", commonName: "Ptolemy Cluster", type: .openCluster,
               rightAscension: 268.4750, declination: -34.8167, magnitude: 3.3,
               majorAxisArcminutes: 80, minorAxisArcminutes: 80, constellation: "Sco"),
        Target(designation: "M8", commonName: "Lagoon Nebula", type: .emissionNebula,
               rightAscension: 270.9500, declination: -24.3833, magnitude: 6.0,
               majorAxisArcminutes: 90, minorAxisArcminutes: 40, constellation: "Sgr"),
        Target(designation: "M9", commonName: nil, type: .globularCluster,
               rightAscension: 259.8000, declination: -18.5167, magnitude: 7.7,
               majorAxisArcminutes: 12, minorAxisArcminutes: 12, constellation: "Oph"),
        Target(designation: "M10", commonName: nil, type: .globularCluster,
               rightAscension: 254.2750, declination: -4.1000, magnitude: 6.6,
               majorAxisArcminutes: 20, minorAxisArcminutes: 20, constellation: "Oph"),
        Target(designation: "M11", commonName: "Wild Duck Cluster", type: .openCluster,
               rightAscension: 282.7750, declination: -6.2667, magnitude: 6.3,
               majorAxisArcminutes: 14, minorAxisArcminutes: 14, constellation: "Sct"),
        Target(designation: "M12", commonName: nil, type: .globularCluster,
               rightAscension: 251.8000, declination: -1.9500, magnitude: 6.7,
               majorAxisArcminutes: 16, minorAxisArcminutes: 16, constellation: "Oph"),
        Target(designation: "M13", commonName: "Hercules Cluster", type: .globularCluster,
               rightAscension: 250.4250, declination: +36.4667, magnitude: 5.8,
               majorAxisArcminutes: 20, minorAxisArcminutes: 20, constellation: "Her"),
        Target(designation: "M14", commonName: nil, type: .globularCluster,
               rightAscension: 264.4000, declination: -3.2500, magnitude: 7.6,
               majorAxisArcminutes: 11, minorAxisArcminutes: 11, constellation: "Oph"),
        Target(designation: "M15", commonName: nil, type: .globularCluster,
               rightAscension: 322.5000, declination: +12.1667, magnitude: 6.2,
               majorAxisArcminutes: 18, minorAxisArcminutes: 18, constellation: "Peg"),
        Target(designation: "M16", commonName: "Eagle Nebula", type: .emissionNebula,
               rightAscension: 274.7000, declination: -13.7833, magnitude: 6.0,
               majorAxisArcminutes: 35, minorAxisArcminutes: 28, constellation: "Ser"),
        Target(designation: "M17", commonName: "Omega Nebula", type: .emissionNebula,
               rightAscension: 275.2000, declination: -16.1833, magnitude: 6.0,
               majorAxisArcminutes: 46, minorAxisArcminutes: 37, constellation: "Sgr"),
        Target(designation: "M18", commonName: nil, type: .openCluster,
               rightAscension: 274.9750, declination: -17.1333, magnitude: 6.9,
               majorAxisArcminutes: 9, minorAxisArcminutes: 9, constellation: "Sgr"),
        Target(designation: "M19", commonName: nil, type: .globularCluster,
               rightAscension: 255.6500, declination: -26.2667, magnitude: 6.8,
               majorAxisArcminutes: 17, minorAxisArcminutes: 17, constellation: "Oph"),
        Target(designation: "M20", commonName: "Trifid Nebula", type: .emissionNebula,
               rightAscension: 270.6500, declination: -23.0333, magnitude: 6.3,
               majorAxisArcminutes: 28, minorAxisArcminutes: 28, constellation: "Sgr"),
        Target(designation: "M21", commonName: nil, type: .openCluster,
               rightAscension: 271.1500, declination: -22.5000, magnitude: 5.9,
               majorAxisArcminutes: 13, minorAxisArcminutes: 13, constellation: "Sgr"),
        Target(designation: "M22", commonName: nil, type: .globularCluster,
               rightAscension: 279.1000, declination: -23.9000, magnitude: 5.1,
               majorAxisArcminutes: 32, minorAxisArcminutes: 32, constellation: "Sgr"),
        Target(designation: "M23", commonName: nil, type: .openCluster,
               rightAscension: 269.2000, declination: -19.0167, magnitude: 5.5,
               majorAxisArcminutes: 27, minorAxisArcminutes: 27, constellation: "Sgr"),
        Target(designation: "M24", commonName: "Sagittarius Star Cloud", type: .starCloud,
               rightAscension: 274.2250, declination: -18.4833, magnitude: 4.6,
               majorAxisArcminutes: 90, minorAxisArcminutes: 60, constellation: "Sgr"),
        Target(designation: "M25", commonName: nil, type: .openCluster,
               rightAscension: 277.9000, declination: -19.2500, magnitude: 4.6,
               majorAxisArcminutes: 32, minorAxisArcminutes: 32, constellation: "Sgr"),
        Target(designation: "M26", commonName: nil, type: .openCluster,
               rightAscension: 281.3000, declination: -9.4000, magnitude: 8.0,
               majorAxisArcminutes: 15, minorAxisArcminutes: 15, constellation: "Sct"),
        Target(designation: "M27", commonName: "Dumbbell Nebula", type: .planetaryNebula,
               rightAscension: 299.9000, declination: +22.7167, magnitude: 7.4,
               majorAxisArcminutes: 8, minorAxisArcminutes: 6, constellation: "Vul"),
        Target(designation: "M28", commonName: nil, type: .globularCluster,
               rightAscension: 276.1250, declination: -24.8667, magnitude: 6.8,
               majorAxisArcminutes: 11, minorAxisArcminutes: 11, constellation: "Sgr"),
        Target(designation: "M29", commonName: nil, type: .openCluster,
               rightAscension: 305.9750, declination: +38.5333, magnitude: 7.1,
               majorAxisArcminutes: 7, minorAxisArcminutes: 7, constellation: "Cyg"),
        Target(designation: "M30", commonName: nil, type: .globularCluster,
               rightAscension: 325.1000, declination: -23.1833, magnitude: 7.2,
               majorAxisArcminutes: 12, minorAxisArcminutes: 12, constellation: "Cap"),
        Target(designation: "M31", commonName: "Andromeda Galaxy", type: .galaxy,
               rightAscension: 10.6750, declination: +41.2667, magnitude: 3.4,
               majorAxisArcminutes: 190, minorAxisArcminutes: 60, constellation: "And"),
        Target(designation: "M32", commonName: nil, type: .galaxy,
               rightAscension: 10.6750, declination: +40.8667, magnitude: 8.1,
               majorAxisArcminutes: 8, minorAxisArcminutes: 6, constellation: "And"),
        Target(designation: "M33", commonName: "Triangulum Galaxy", type: .galaxy,
               rightAscension: 23.4750, declination: +30.6500, magnitude: 5.7,
               majorAxisArcminutes: 70, minorAxisArcminutes: 41, constellation: "Tri"),
        Target(designation: "M34", commonName: nil, type: .openCluster,
               rightAscension: 40.5000, declination: +42.7833, magnitude: 5.5,
               majorAxisArcminutes: 35, minorAxisArcminutes: 35, constellation: "Per"),
        Target(designation: "M35", commonName: nil, type: .openCluster,
               rightAscension: 92.2250, declination: +24.3333, magnitude: 5.3,
               majorAxisArcminutes: 28, minorAxisArcminutes: 28, constellation: "Gem"),
        Target(designation: "M36", commonName: nil, type: .openCluster,
               rightAscension: 84.0250, declination: +34.1333, magnitude: 6.3,
               majorAxisArcminutes: 12, minorAxisArcminutes: 12, constellation: "Aur"),
        Target(designation: "M37", commonName: nil, type: .openCluster,
               rightAscension: 88.1000, declination: +32.5500, magnitude: 6.2,
               majorAxisArcminutes: 24, minorAxisArcminutes: 24, constellation: "Aur"),
        Target(designation: "M38", commonName: nil, type: .openCluster,
               rightAscension: 82.1000, declination: +35.8333, magnitude: 7.4,
               majorAxisArcminutes: 21, minorAxisArcminutes: 21, constellation: "Aur"),
        Target(designation: "M39", commonName: nil, type: .openCluster,
               rightAscension: 323.0500, declination: +48.4333, magnitude: 4.6,
               majorAxisArcminutes: 32, minorAxisArcminutes: 32, constellation: "Cyg"),
        Target(designation: "M40", commonName: "Winnecke 4", type: .asterism,
               rightAscension: 185.6000, declination: +58.0833, magnitude: 8.4,
               majorAxisArcminutes: 1, minorAxisArcminutes: 1, constellation: "UMa"),
        Target(designation: "M41", commonName: nil, type: .openCluster,
               rightAscension: 101.5000, declination: -20.7333, magnitude: 4.5,
               majorAxisArcminutes: 38, minorAxisArcminutes: 38, constellation: "CMa"),
        Target(designation: "M42", commonName: "Orion Nebula", type: .emissionNebula,
               rightAscension: 83.8500, declination: -5.4500, magnitude: 4.0,
               majorAxisArcminutes: 85, minorAxisArcminutes: 60, constellation: "Ori"),
        Target(designation: "M43", commonName: "De Mairan's Nebula", type: .emissionNebula,
               rightAscension: 83.9000, declination: -5.2667, magnitude: 9.0,
               majorAxisArcminutes: 20, minorAxisArcminutes: 15, constellation: "Ori"),
        Target(designation: "M44", commonName: "Beehive Cluster", type: .openCluster,
               rightAscension: 130.0250, declination: +19.9833, magnitude: 3.7,
               majorAxisArcminutes: 95, minorAxisArcminutes: 95, constellation: "Cnc"),
        Target(designation: "M45", commonName: "Pleiades", type: .openCluster,
               rightAscension: 56.7500, declination: +24.1167, magnitude: 1.6,
               majorAxisArcminutes: 110, minorAxisArcminutes: 110, constellation: "Tau"),
        Target(designation: "M46", commonName: nil, type: .openCluster,
               rightAscension: 115.4500, declination: -14.8167, magnitude: 6.1,
               majorAxisArcminutes: 27, minorAxisArcminutes: 27, constellation: "Pup"),
        Target(designation: "M47", commonName: nil, type: .openCluster,
               rightAscension: 114.1500, declination: -14.5000, magnitude: 4.4,
               majorAxisArcminutes: 30, minorAxisArcminutes: 30, constellation: "Pup"),
        Target(designation: "M48", commonName: nil, type: .openCluster,
               rightAscension: 123.4500, declination: -5.8000, magnitude: 5.8,
               majorAxisArcminutes: 54, minorAxisArcminutes: 54, constellation: "Hya"),
        Target(designation: "M49", commonName: nil, type: .galaxy,
               rightAscension: 187.4500, declination: +8.0000, magnitude: 8.4,
               majorAxisArcminutes: 9, minorAxisArcminutes: 7, constellation: "Vir"),
        Target(designation: "M50", commonName: nil, type: .openCluster,
               rightAscension: 105.8000, declination: -8.3333, magnitude: 5.9,
               majorAxisArcminutes: 16, minorAxisArcminutes: 16, constellation: "Mon"),
        Target(designation: "M51", commonName: "Whirlpool Galaxy", type: .galaxy,
               rightAscension: 202.4750, declination: +47.2000, magnitude: 8.4,
               majorAxisArcminutes: 11, minorAxisArcminutes: 7, constellation: "CVn"),
        Target(designation: "M52", commonName: nil, type: .openCluster,
               rightAscension: 351.0500, declination: +61.5833, magnitude: 6.9,
               majorAxisArcminutes: 13, minorAxisArcminutes: 13, constellation: "Cas"),
        Target(designation: "M53", commonName: nil, type: .globularCluster,
               rightAscension: 198.2250, declination: +18.1667, magnitude: 7.6,
               majorAxisArcminutes: 13, minorAxisArcminutes: 13, constellation: "Com"),
        Target(designation: "M54", commonName: nil, type: .globularCluster,
               rightAscension: 283.7750, declination: -30.4833, magnitude: 7.6,
               majorAxisArcminutes: 12, minorAxisArcminutes: 12, constellation: "Sgr"),
        Target(designation: "M55", commonName: nil, type: .globularCluster,
               rightAscension: 295.0000, declination: -30.9667, magnitude: 6.3,
               majorAxisArcminutes: 19, minorAxisArcminutes: 19, constellation: "Sgr"),
        Target(designation: "M56", commonName: nil, type: .globularCluster,
               rightAscension: 289.1500, declination: +30.1833, magnitude: 8.3,
               majorAxisArcminutes: 7, minorAxisArcminutes: 7, constellation: "Lyr"),
        Target(designation: "M57", commonName: "Ring Nebula", type: .planetaryNebula,
               rightAscension: 283.4000, declination: +33.0333, magnitude: 8.8,
               majorAxisArcminutes: 1.4, minorAxisArcminutes: 1, constellation: "Lyr"),
        Target(designation: "M58", commonName: nil, type: .galaxy,
               rightAscension: 189.4250, declination: +11.8167, magnitude: 9.7,
               majorAxisArcminutes: 6, minorAxisArcminutes: 5, constellation: "Vir"),
        Target(designation: "M59", commonName: nil, type: .galaxy,
               rightAscension: 190.5000, declination: +11.6500, magnitude: 9.6,
               majorAxisArcminutes: 5, minorAxisArcminutes: 3.5, constellation: "Vir"),
        Target(designation: "M60", commonName: nil, type: .galaxy,
               rightAscension: 190.9250, declination: +11.5500, magnitude: 8.8,
               majorAxisArcminutes: 7, minorAxisArcminutes: 6, constellation: "Vir"),
        Target(designation: "M61", commonName: nil, type: .galaxy,
               rightAscension: 185.4750, declination: +4.4667, magnitude: 9.7,
               majorAxisArcminutes: 6, minorAxisArcminutes: 5.5, constellation: "Vir"),
        Target(designation: "M62", commonName: nil, type: .globularCluster,
               rightAscension: 255.3000, declination: -30.1167, magnitude: 6.5,
               majorAxisArcminutes: 15, minorAxisArcminutes: 15, constellation: "Oph"),
        Target(designation: "M63", commonName: "Sunflower Galaxy", type: .galaxy,
               rightAscension: 198.9500, declination: +42.0333, magnitude: 8.6,
               majorAxisArcminutes: 12, minorAxisArcminutes: 8, constellation: "CVn"),
        Target(designation: "M64", commonName: "Black Eye Galaxy", type: .galaxy,
               rightAscension: 194.1750, declination: +21.6833, magnitude: 8.5,
               majorAxisArcminutes: 9, minorAxisArcminutes: 5, constellation: "Com"),
        Target(designation: "M65", commonName: nil, type: .galaxy,
               rightAscension: 169.7250, declination: +13.0833, magnitude: 9.3,
               majorAxisArcminutes: 10, minorAxisArcminutes: 3, constellation: "Leo"),
        Target(designation: "M66", commonName: nil, type: .galaxy,
               rightAscension: 170.0500, declination: +12.9833, magnitude: 8.9,
               majorAxisArcminutes: 9, minorAxisArcminutes: 4, constellation: "Leo"),
        Target(designation: "M67", commonName: nil, type: .openCluster,
               rightAscension: 132.8500, declination: +11.8167, magnitude: 6.1,
               majorAxisArcminutes: 30, minorAxisArcminutes: 30, constellation: "Cnc"),
        Target(designation: "M68", commonName: nil, type: .globularCluster,
               rightAscension: 189.8750, declination: -26.7500, magnitude: 7.8,
               majorAxisArcminutes: 12, minorAxisArcminutes: 12, constellation: "Hya"),
        Target(designation: "M69", commonName: nil, type: .globularCluster,
               rightAscension: 277.8500, declination: -32.3500, magnitude: 7.6,
               majorAxisArcminutes: 10, minorAxisArcminutes: 10, constellation: "Sgr"),
        Target(designation: "M70", commonName: nil, type: .globularCluster,
               rightAscension: 280.8000, declination: -32.3000, magnitude: 7.9,
               majorAxisArcminutes: 8, minorAxisArcminutes: 8, constellation: "Sgr"),
        Target(designation: "M71", commonName: nil, type: .globularCluster,
               rightAscension: 298.4500, declination: +18.7833, magnitude: 8.2,
               majorAxisArcminutes: 7, minorAxisArcminutes: 7, constellation: "Sge"),
        Target(designation: "M72", commonName: nil, type: .globularCluster,
               rightAscension: 313.3750, declination: -12.5333, magnitude: 9.3,
               majorAxisArcminutes: 6, minorAxisArcminutes: 6, constellation: "Aqr"),
        Target(designation: "M73", commonName: nil, type: .asterism,
               rightAscension: 314.7500, declination: -12.6333, magnitude: 9.0,
               majorAxisArcminutes: 3, minorAxisArcminutes: 3, constellation: "Aqr"),
        Target(designation: "M74", commonName: "Phantom Galaxy", type: .galaxy,
               rightAscension: 24.1750, declination: +15.7833, magnitude: 9.4,
               majorAxisArcminutes: 10, minorAxisArcminutes: 9, constellation: "Psc"),
        Target(designation: "M75", commonName: nil, type: .globularCluster,
               rightAscension: 301.5250, declination: -21.9167, magnitude: 8.5,
               majorAxisArcminutes: 6, minorAxisArcminutes: 6, constellation: "Sgr"),
        Target(designation: "M76", commonName: "Little Dumbbell", type: .planetaryNebula,
               rightAscension: 25.6000, declination: +51.5667, magnitude: 10.1,
               majorAxisArcminutes: 3, minorAxisArcminutes: 2, constellation: "Per"),
        Target(designation: "M77", commonName: nil, type: .galaxy,
               rightAscension: 40.6750, declination: -0.0167, magnitude: 8.9,
               majorAxisArcminutes: 7, minorAxisArcminutes: 6, constellation: "Cet"),
        Target(designation: "M78", commonName: nil, type: .reflectionNebula,
               rightAscension: 86.6750, declination: +0.0500, magnitude: 8.3,
               majorAxisArcminutes: 8, minorAxisArcminutes: 6, constellation: "Ori"),
        Target(designation: "M79", commonName: nil, type: .globularCluster,
               rightAscension: 81.1250, declination: -24.5500, magnitude: 7.7,
               majorAxisArcminutes: 9, minorAxisArcminutes: 9, constellation: "Lep"),
        Target(designation: "M80", commonName: nil, type: .globularCluster,
               rightAscension: 244.2500, declination: -22.9833, magnitude: 7.3,
               majorAxisArcminutes: 10, minorAxisArcminutes: 10, constellation: "Sco"),
        Target(designation: "M81", commonName: "Bode's Galaxy", type: .galaxy,
               rightAscension: 148.9000, declination: +69.0667, magnitude: 6.9,
               majorAxisArcminutes: 27, minorAxisArcminutes: 14, constellation: "UMa"),
        Target(designation: "M82", commonName: "Cigar Galaxy", type: .galaxy,
               rightAscension: 148.9500, declination: +69.6833, magnitude: 8.4,
               majorAxisArcminutes: 11, minorAxisArcminutes: 4, constellation: "UMa"),
        Target(designation: "M83", commonName: "Southern Pinwheel", type: .galaxy,
               rightAscension: 204.2500, declination: -29.8667, magnitude: 7.5,
               majorAxisArcminutes: 13, minorAxisArcminutes: 12, constellation: "Hya"),
        Target(designation: "M84", commonName: nil, type: .galaxy,
               rightAscension: 186.2750, declination: +12.8833, magnitude: 9.1,
               majorAxisArcminutes: 5, minorAxisArcminutes: 5, constellation: "Vir"),
        Target(designation: "M85", commonName: nil, type: .galaxy,
               rightAscension: 186.3500, declination: +18.1833, magnitude: 9.1,
               majorAxisArcminutes: 7, minorAxisArcminutes: 5, constellation: "Com"),
        Target(designation: "M86", commonName: nil, type: .galaxy,
               rightAscension: 186.5500, declination: +12.9500, magnitude: 8.9,
               majorAxisArcminutes: 9, minorAxisArcminutes: 6, constellation: "Vir"),
        Target(designation: "M87", commonName: "Virgo A", type: .galaxy,
               rightAscension: 187.7000, declination: +12.4000, magnitude: 8.6,
               majorAxisArcminutes: 7, minorAxisArcminutes: 7, constellation: "Vir"),
        Target(designation: "M88", commonName: nil, type: .galaxy,
               rightAscension: 188.0000, declination: +14.4167, magnitude: 9.6,
               majorAxisArcminutes: 7, minorAxisArcminutes: 4, constellation: "Com"),
        Target(designation: "M89", commonName: nil, type: .galaxy,
               rightAscension: 188.9250, declination: +12.5500, magnitude: 9.8,
               majorAxisArcminutes: 4, minorAxisArcminutes: 4, constellation: "Vir"),
        Target(designation: "M90", commonName: nil, type: .galaxy,
               rightAscension: 189.2000, declination: +13.1667, magnitude: 9.5,
               majorAxisArcminutes: 9, minorAxisArcminutes: 4, constellation: "Vir"),
        Target(designation: "M91", commonName: nil, type: .galaxy,
               rightAscension: 188.8500, declination: +14.5000, magnitude: 10.2,
               majorAxisArcminutes: 5, minorAxisArcminutes: 4, constellation: "Com"),
        Target(designation: "M92", commonName: nil, type: .globularCluster,
               rightAscension: 259.2750, declination: +43.1333, magnitude: 6.4,
               majorAxisArcminutes: 14, minorAxisArcminutes: 14, constellation: "Her"),
        Target(designation: "M93", commonName: nil, type: .openCluster,
               rightAscension: 116.1500, declination: -23.8667, magnitude: 6.2,
               majorAxisArcminutes: 22, minorAxisArcminutes: 22, constellation: "Pup"),
        Target(designation: "M94", commonName: nil, type: .galaxy,
               rightAscension: 192.7250, declination: +41.1167, magnitude: 8.2,
               majorAxisArcminutes: 11, minorAxisArcminutes: 9, constellation: "CVn"),
        Target(designation: "M95", commonName: nil, type: .galaxy,
               rightAscension: 161.0000, declination: +11.7000, magnitude: 9.7,
               majorAxisArcminutes: 7, minorAxisArcminutes: 5, constellation: "Leo"),
        Target(designation: "M96", commonName: nil, type: .galaxy,
               rightAscension: 161.7000, declination: +11.8167, magnitude: 9.2,
               majorAxisArcminutes: 7, minorAxisArcminutes: 5, constellation: "Leo"),
        Target(designation: "M97", commonName: "Owl Nebula", type: .planetaryNebula,
               rightAscension: 168.7000, declination: +55.0167, magnitude: 9.9,
               majorAxisArcminutes: 3.4, minorAxisArcminutes: 3.3, constellation: "UMa"),
        Target(designation: "M98", commonName: nil, type: .galaxy,
               rightAscension: 183.4500, declination: +14.9000, magnitude: 10.1,
               majorAxisArcminutes: 10, minorAxisArcminutes: 3, constellation: "Com"),
        Target(designation: "M99", commonName: nil, type: .galaxy,
               rightAscension: 184.7000, declination: +14.4167, magnitude: 9.9,
               majorAxisArcminutes: 5, minorAxisArcminutes: 5, constellation: "Com"),
        Target(designation: "M100", commonName: nil, type: .galaxy,
               rightAscension: 185.7250, declination: +15.8167, magnitude: 9.3,
               majorAxisArcminutes: 7, minorAxisArcminutes: 6, constellation: "Com"),
        Target(designation: "M101", commonName: "Pinwheel Galaxy", type: .galaxy,
               rightAscension: 210.8000, declination: +54.3500, magnitude: 7.9,
               majorAxisArcminutes: 29, minorAxisArcminutes: 27, constellation: "UMa"),
        Target(designation: "M102", commonName: "Spindle Galaxy", type: .galaxy,
               rightAscension: 226.6250, declination: +55.7667, magnitude: 9.9,
               majorAxisArcminutes: 5, minorAxisArcminutes: 2, constellation: "Dra"),
        Target(designation: "M103", commonName: nil, type: .openCluster,
               rightAscension: 23.3000, declination: +60.7000, magnitude: 7.4,
               majorAxisArcminutes: 6, minorAxisArcminutes: 6, constellation: "Cas"),
        Target(designation: "M104", commonName: "Sombrero Galaxy", type: .galaxy,
               rightAscension: 190.0000, declination: -11.6167, magnitude: 8.0,
               majorAxisArcminutes: 9, minorAxisArcminutes: 4, constellation: "Vir"),
        Target(designation: "M105", commonName: nil, type: .galaxy,
               rightAscension: 161.9500, declination: +12.5833, magnitude: 9.3,
               majorAxisArcminutes: 5, minorAxisArcminutes: 5, constellation: "Leo"),
        Target(designation: "M106", commonName: nil, type: .galaxy,
               rightAscension: 184.7500, declination: +47.3000, magnitude: 8.4,
               majorAxisArcminutes: 19, minorAxisArcminutes: 8, constellation: "CVn"),
        Target(designation: "M107", commonName: nil, type: .globularCluster,
               rightAscension: 248.1250, declination: -13.0500, magnitude: 8.1,
               majorAxisArcminutes: 10, minorAxisArcminutes: 10, constellation: "Oph"),
        Target(designation: "M108", commonName: nil, type: .galaxy,
               rightAscension: 167.8750, declination: +55.6667, magnitude: 10.0,
               majorAxisArcminutes: 8, minorAxisArcminutes: 2, constellation: "UMa"),
        Target(designation: "M109", commonName: nil, type: .galaxy,
               rightAscension: 179.4000, declination: +53.3667, magnitude: 9.8,
               majorAxisArcminutes: 8, minorAxisArcminutes: 5, constellation: "UMa"),
        Target(designation: "M110", commonName: nil, type: .galaxy,
               rightAscension: 10.1000, declination: +41.6833, magnitude: 8.5,
               majorAxisArcminutes: 17, minorAxisArcminutes: 10, constellation: "And"),
    ]

    static let showpieces: [Target] = [
        Target(designation: "NGC 7000", commonName: "North America Nebula", type: .emissionNebula,
               rightAscension: 314.7000, declination: +44.3333, magnitude: 4.0,
               majorAxisArcminutes: 120, minorAxisArcminutes: 100, constellation: "Cyg"),
        Target(designation: "IC 5070", commonName: "Pelican Nebula", type: .emissionNebula,
               rightAscension: 312.7000, declination: +44.3500, magnitude: 8.0,
               majorAxisArcminutes: 60, minorAxisArcminutes: 50, constellation: "Cyg"),
        Target(designation: "NGC 6960", commonName: "Western Veil", type: .supernovaRemnant,
               rightAscension: 311.4250, declination: +30.7167, magnitude: 7.0,
               majorAxisArcminutes: 70, minorAxisArcminutes: 6, constellation: "Cyg"),
        Target(designation: "NGC 6992", commonName: "Eastern Veil", type: .supernovaRemnant,
               rightAscension: 314.1000, declination: +31.7167, magnitude: 7.0,
               majorAxisArcminutes: 60, minorAxisArcminutes: 8, constellation: "Cyg"),
        Target(designation: "NGC 6888", commonName: "Crescent Nebula", type: .emissionNebula,
               rightAscension: 303.1750, declination: +38.3500, magnitude: 7.4,
               majorAxisArcminutes: 18, minorAxisArcminutes: 12, constellation: "Cyg"),
        Target(designation: "NGC 7635", commonName: "Bubble Nebula", type: .emissionNebula,
               rightAscension: 350.1750, declination: +61.2000, magnitude: 10.0,
               majorAxisArcminutes: 15, minorAxisArcminutes: 8, constellation: "Cas"),
        Target(designation: "NGC 281", commonName: "Pacman Nebula", type: .emissionNebula,
               rightAscension: 13.2000, declination: +56.6000, magnitude: 7.4,
               majorAxisArcminutes: 35, minorAxisArcminutes: 30, constellation: "Cas"),
        Target(designation: "IC 1805", commonName: "Heart Nebula", type: .emissionNebula,
               rightAscension: 38.1750, declination: +61.4500, magnitude: 6.5,
               majorAxisArcminutes: 150, minorAxisArcminutes: 150, constellation: "Cas"),
        Target(designation: "IC 1848", commonName: "Soul Nebula", type: .emissionNebula,
               rightAscension: 42.9000, declination: +60.4333, magnitude: 6.5,
               majorAxisArcminutes: 100, minorAxisArcminutes: 60, constellation: "Cas"),
        Target(designation: "NGC 869", commonName: "Double Cluster", type: .openCluster,
               rightAscension: 35.0000, declination: +57.1333, magnitude: 4.3,
               majorAxisArcminutes: 60, minorAxisArcminutes: 30, constellation: "Per"),
        Target(designation: "NGC 1499", commonName: "California Nebula", type: .emissionNebula,
               rightAscension: 60.8250, declination: +36.4167, magnitude: 6.0,
               majorAxisArcminutes: 160, minorAxisArcminutes: 40, constellation: "Per"),
        Target(designation: "NGC 1333", commonName: nil, type: .reflectionNebula,
               rightAscension: 52.3250, declination: +31.4167, magnitude: 5.6,
               majorAxisArcminutes: 9, minorAxisArcminutes: 7, constellation: "Per"),
        Target(designation: "IC 434", commonName: "Horsehead Nebula", type: .emissionNebula,
               rightAscension: 85.2500, declination: -2.4500, magnitude: 6.8,
               majorAxisArcminutes: 60, minorAxisArcminutes: 10, constellation: "Ori"),
        Target(designation: "NGC 2024", commonName: "Flame Nebula", type: .emissionNebula,
               rightAscension: 85.4750, declination: -1.8500, magnitude: 10.0,
               majorAxisArcminutes: 30, minorAxisArcminutes: 30, constellation: "Ori"),
        Target(designation: "NGC 2237", commonName: "Rosette Nebula", type: .emissionNebula,
               rightAscension: 97.9250, declination: +4.9833, magnitude: 5.5,
               majorAxisArcminutes: 80, minorAxisArcminutes: 60, constellation: "Mon"),
        Target(designation: "NGC 2264", commonName: "Christmas Tree Cluster", type: .emissionNebula,
               rightAscension: 100.2750, declination: +9.8833, magnitude: 3.9,
               majorAxisArcminutes: 60, minorAxisArcminutes: 30, constellation: "Mon"),
        Target(designation: "IC 443", commonName: "Jellyfish Nebula", type: .supernovaRemnant,
               rightAscension: 94.4500, declination: +22.5167, magnitude: 12.0,
               majorAxisArcminutes: 50, minorAxisArcminutes: 40, constellation: "Gem"),
        Target(designation: "IC 405", commonName: "Flaming Star Nebula", type: .emissionNebula,
               rightAscension: 79.0500, declination: +34.2667, magnitude: 6.0,
               majorAxisArcminutes: 37, minorAxisArcminutes: 19, constellation: "Aur"),
        Target(designation: "IC 410", commonName: "Tadpoles Nebula", type: .emissionNebula,
               rightAscension: 80.6500, declination: +33.5167, magnitude: 7.5,
               majorAxisArcminutes: 40, minorAxisArcminutes: 30, constellation: "Aur"),
        Target(designation: "NGC 2359", commonName: "Thor's Helmet", type: .emissionNebula,
               rightAscension: 109.6500, declination: -13.2000, magnitude: 11.5,
               majorAxisArcminutes: 8, minorAxisArcminutes: 6, constellation: "CMa"),
        Target(designation: "NGC 2392", commonName: "Eskimo Nebula", type: .planetaryNebula,
               rightAscension: 112.3000, declination: +20.9167, magnitude: 9.2,
               majorAxisArcminutes: 0.8, minorAxisArcminutes: 0.8, constellation: "Gem"),
        Target(designation: "NGC 7293", commonName: "Helix Nebula", type: .planetaryNebula,
               rightAscension: 337.4000, declination: -20.8000, magnitude: 7.3,
               majorAxisArcminutes: 16, minorAxisArcminutes: 16, constellation: "Aqr"),
        Target(designation: "NGC 7009", commonName: "Saturn Nebula", type: .planetaryNebula,
               rightAscension: 316.0500, declination: -11.3667, magnitude: 8.0,
               majorAxisArcminutes: 1.6, minorAxisArcminutes: 1.6, constellation: "Aqr"),
        Target(designation: "NGC 6543", commonName: "Cat's Eye Nebula", type: .planetaryNebula,
               rightAscension: 269.6500, declination: +66.6333, magnitude: 8.1,
               majorAxisArcminutes: 5.8, minorAxisArcminutes: 5.8, constellation: "Dra"),
        Target(designation: "NGC 6302", commonName: "Bug Nebula", type: .planetaryNebula,
               rightAscension: 258.4250, declination: -37.1000, magnitude: 9.6,
               majorAxisArcminutes: 3, minorAxisArcminutes: 1, constellation: "Sco"),
        Target(designation: "NGC 7380", commonName: "Wizard Nebula", type: .emissionNebula,
               rightAscension: 341.7500, declination: +58.1000, magnitude: 7.2,
               majorAxisArcminutes: 25, minorAxisArcminutes: 20, constellation: "Cep"),
        Target(designation: "IC 1396", commonName: "Elephant's Trunk", type: .emissionNebula,
               rightAscension: 324.7750, declination: +57.5000, magnitude: 3.5,
               majorAxisArcminutes: 170, minorAxisArcminutes: 140, constellation: "Cep"),
        Target(designation: "Sh2-155", commonName: "Cave Nebula", type: .emissionNebula,
               rightAscension: 344.2000, declination: +62.6167, magnitude: 7.7,
               majorAxisArcminutes: 50, minorAxisArcminutes: 30, constellation: "Cep"),
        Target(designation: "NGC 7023", commonName: "Iris Nebula", type: .reflectionNebula,
               rightAscension: 315.4000, declination: +68.1667, magnitude: 6.8,
               majorAxisArcminutes: 18, minorAxisArcminutes: 18, constellation: "Cep"),
        Target(designation: "NGC 6946", commonName: "Fireworks Galaxy", type: .galaxy,
               rightAscension: 308.7250, declination: +60.1500, magnitude: 8.8,
               majorAxisArcminutes: 11, minorAxisArcminutes: 10, constellation: "Cep"),
        Target(designation: "NGC 7331", commonName: nil, type: .galaxy,
               rightAscension: 339.2750, declination: +34.4167, magnitude: 9.5,
               majorAxisArcminutes: 10, minorAxisArcminutes: 4, constellation: "Peg"),
        Target(designation: "NGC 253", commonName: "Sculptor Galaxy", type: .galaxy,
               rightAscension: 11.9000, declination: -25.2833, magnitude: 7.1,
               majorAxisArcminutes: 28, minorAxisArcminutes: 7, constellation: "Scl"),
        Target(designation: "NGC 891", commonName: nil, type: .galaxy,
               rightAscension: 35.6500, declination: +42.3500, magnitude: 10.0,
               majorAxisArcminutes: 14, minorAxisArcminutes: 2.5, constellation: "And"),
        Target(designation: "NGC 4565", commonName: "Needle Galaxy", type: .galaxy,
               rightAscension: 189.0750, declination: +25.9833, magnitude: 9.6,
               majorAxisArcminutes: 16, minorAxisArcminutes: 2, constellation: "Com"),
        Target(designation: "NGC 4631", commonName: "Whale Galaxy", type: .galaxy,
               rightAscension: 190.5250, declination: +32.5333, magnitude: 9.2,
               majorAxisArcminutes: 15, minorAxisArcminutes: 3, constellation: "CVn"),
        Target(designation: "NGC 5907", commonName: "Splinter Galaxy", type: .galaxy,
               rightAscension: 228.9750, declination: +56.3167, magnitude: 10.3,
               majorAxisArcminutes: 12, minorAxisArcminutes: 2, constellation: "Dra"),
        Target(designation: "NGC 3628", commonName: "Hamburger Galaxy", type: .galaxy,
               rightAscension: 170.0750, declination: +13.5833, magnitude: 10.2,
               majorAxisArcminutes: 15, minorAxisArcminutes: 4, constellation: "Leo"),
        Target(designation: "NGC 2903", commonName: nil, type: .galaxy,
               rightAscension: 143.0500, declination: +21.5000, magnitude: 9.0,
               majorAxisArcminutes: 12, minorAxisArcminutes: 6, constellation: "Leo"),
        Target(designation: "NGC 4038", commonName: "Antennae Galaxies", type: .galaxyGroup,
               rightAscension: 180.4750, declination: -18.8667, magnitude: 10.3,
               majorAxisArcminutes: 5, minorAxisArcminutes: 3, constellation: "Crv"),
        Target(designation: "Markarian's Chain", commonName: nil, type: .galaxyGroup,
               rightAscension: 186.7500, declination: +13.0000, magnitude: 9.0,
               majorAxisArcminutes: 90, minorAxisArcminutes: 30, constellation: "Vir"),
        Target(designation: "NGC 6822", commonName: "Barnard's Galaxy", type: .galaxy,
               rightAscension: 296.2250, declination: -14.8000, magnitude: 8.7,
               majorAxisArcminutes: 15, minorAxisArcminutes: 14, constellation: "Sgr"),
        Target(designation: "NGC 5128", commonName: "Centaurus A", type: .galaxy,
               rightAscension: 201.3750, declination: -43.0167, magnitude: 6.8,
               majorAxisArcminutes: 26, minorAxisArcminutes: 20, constellation: "Cen"),
        Target(designation: "NGC 5139", commonName: "Omega Centauri", type: .globularCluster,
               rightAscension: 201.7000, declination: -47.4833, magnitude: 3.9,
               majorAxisArcminutes: 55, minorAxisArcminutes: 55, constellation: "Cen"),
        Target(designation: "NGC 3372", commonName: "Eta Carinae Nebula", type: .emissionNebula,
               rightAscension: 161.2750, declination: -59.8667, magnitude: 1.0,
               majorAxisArcminutes: 120, minorAxisArcminutes: 120, constellation: "Car"),
        Target(designation: "NGC 104", commonName: "47 Tucanae", type: .globularCluster,
               rightAscension: 6.0250, declination: -72.0833, magnitude: 4.0,
               majorAxisArcminutes: 50, minorAxisArcminutes: 50, constellation: "Tuc"),
        Target(designation: "LMC", commonName: "Large Magellanic Cloud", type: .galaxy,
               rightAscension: 80.9000, declination: -69.7500, magnitude: 0.9,
               majorAxisArcminutes: 645, minorAxisArcminutes: 550, constellation: "Dor"),
        Target(designation: "SMC", commonName: "Small Magellanic Cloud", type: .galaxy,
               rightAscension: 13.1500, declination: -72.8000, magnitude: 2.7,
               majorAxisArcminutes: 320, minorAxisArcminutes: 185, constellation: "Tuc"),
        Target(designation: "NGC 2070", commonName: "Tarantula Nebula", type: .emissionNebula,
               rightAscension: 84.6500, declination: -69.1000, magnitude: 8.0,
               majorAxisArcminutes: 40, minorAxisArcminutes: 25, constellation: "Dor"),
        Target(designation: "NGC 6334", commonName: "Cat's Paw Nebula", type: .emissionNebula,
               rightAscension: 260.2000, declination: -36.1000, magnitude: 5.5,
               majorAxisArcminutes: 40, minorAxisArcminutes: 30, constellation: "Sco"),
    ]

    /// The ~1000 brightest NGC/IC objects not already covered by `messier` or
    /// `showpieces`, generated from the OpenNGC database (CC-BY-SA-4.0; see
    /// Scripts/build_extended_catalog.py) rather than hand-typed — accurate
    /// astronomical data at this scale isn't something to type from memory.
    static let extended: [Target] = {
        guard let url = Bundle.main.url(forResource: "ExtendedCatalog", withExtension: "json"),
              let data = try? Data(contentsOf: url),
              let decoded = try? JSONDecoder().decode([Target].self, from: data)
        else { return [] }
        return decoded
    }()

    static let all: [Target] = messier + showpieces + extended
}
