#!/usr/bin/env python3
"""Writes a slimmed copy of the Swift Wasm SDK's ICU data as a C file.

Foundation on WebAssembly links all of ICU's data (~34 MB) — every language,
collation, converter and break rule. The engine only formats times and dates in
English and needs time zones, so this keeps those and drops the rest. The C
file defines `icudt76_dat` itself, so the linker never pulls the SDK's copy out
of lib_FoundationICU.a.

    slim_icu.py <lib_FoundationICU.a member icu_packaged_data.cpp.obj> <out.c>

If the engine ever needs a dropped item, it shows up as a mismatch in
web/scripts/parity.mjs; add it to KEEP below.
"""
import re, struct, sys

KEEP = [
    r'(root|pool|res_index|en|en_001|en_US|en_US_POSIX)\.res',
    r'(supplementalData|likelySubtags|zoneinfo64|metaZones|timezoneTypes|windowsZones|icuver|icustd'
    r'|numberingSystems|dayPeriods|plurals|pluralRanges|keyTypeData|metadata|grammaticalFeatures|genderList)\.res',
    r'(cnvalias|uemoji|ulayout)\.icu',
    r'[a-z0-9_]+\.nrm',
    r'zone/(root|pool|res_index|en|en_001|en_US|tzdbNames)\.res',
]

def wasm_data_segment(path):
    d = open(path, 'rb').read()
    def leb(i):
        r = s = 0
        while True:
            b = d[i]; i += 1; r |= (b & 0x7f) << s; s += 7
            if b < 0x80: return r, i
    i = 8
    while i < len(d):
        sid = d[i]; i += 1
        n, i = leb(i)
        if sid == 11:
            count, j = leb(i); assert count == 1
            flags, j = leb(j); assert flags == 0 and d[j] == 0x41
            _, j = leb(j + 1); assert d[j] == 0x0b
            size, j = leb(j + 1)
            return d[j:j + size]
        i += n
    raise SystemExit('no data segment')

def read_items(dat):
    header_size = struct.unpack_from('<H', dat, 0)[0]
    toc = dat[header_size:]
    count = struct.unpack_from('<I', toc, 0)[0]
    entries = [struct.unpack_from('<II', toc, 4 + 8 * k) for k in range(count)]
    items = []
    for k, (name_offset, data_offset) in enumerate(entries):
        name = toc[name_offset:toc.index(b'\0', name_offset)].decode()
        end = entries[k + 1][1] if k + 1 < count else len(toc)
        items.append((name, toc[data_offset:end]))
    return dat[:header_size], items

def write_dat(header, items):
    count = len(items)
    names = b''.join(n.encode() + b'\0' for n, _ in items)
    names_start = 4 + 8 * count
    data_start = (names_start + len(names) + 15) & ~15
    entries, blobs, name_pos, data_pos = b'', b'', names_start, data_start
    for name, blob in items:
        entries += struct.pack('<II', name_pos, data_pos)
        name_pos += len(name.encode()) + 1
        padded = blob + b'\0' * (-len(blob) % 16)
        blobs += padded
        data_pos += len(padded)
    toc = struct.pack('<I', count) + entries + names
    toc += b'\0' * (data_start - len(toc))
    return header + toc + blobs

def main(obj, out):
    header, items = read_items(wasm_data_segment(obj))
    prefix = items[0][0].split('/')[0] + '/'
    keep = [re.compile(prefix + p + '$') for p in KEEP]
    kept = [(n, b) for n, b in items if any(k.match(n) for k in keep)]
    dat = write_dat(header, kept)
    with open(out, 'w') as f:
        f.write('// Generated by slim_icu.py — do not edit.\n')
        f.write('__attribute__((aligned(16))) const unsigned char icudt76_dat[%d] = {\n' % len(dat))
        for i in range(0, len(dat), 32):
            f.write(','.join(str(b) for b in dat[i:i + 32]) + ',\n')
        f.write('};\n')
    print(f'ICU data: kept {len(kept)} of {len(items)} items, {len(dat) / 1e6:.2f} MB')

if __name__ == '__main__':
    main(*sys.argv[1:])
