import SwiftUI

/// A colour-key row, so a help section can point at the exact hue used
/// on-screen rather than just naming it.
struct HelpSwatch: Identifiable {
    var id: String { label }
    var color: Color
    var label: String
}

/// One block of explanatory text, with an optional heading and an optional
/// row of colour swatches for anything that leans on colour to communicate.
struct HelpSection: Identifiable {
    var id: String { heading ?? body }
    var heading: String?
    var body: String
    var swatches: [HelpSwatch] = []
}

struct HelpTopic: Identifiable {
    var id: String { title }
    var title: String
    var systemImage: String
    var sections: [HelpSection]
}

enum HelpContent {
    static let topics: [HelpTopic] = [
        HelpTopic(title: "Scores & Verdicts", systemImage: "target", sections: [
            HelpSection(body: "Every night and every target gets a score from 0 to 100, shown in the coloured circle — a weighted geometric mean of several factors (each on a 0 to 1 scale), not a simple average. A geometric mean punishes a single near-zero factor — no clear sky, say, or no time above the horizon — hard, rather than letting good scores elsewhere paper over it."),
            HelpSection(heading: "The Coloured Tag", body: "Each score is grouped into one of five verdicts, shown as a coloured pill beside the date or target name. All five sit on one red-to-green scale, so colour means the same thing everywhere in the app: red is worse, green is better. Exceptional gets a brighter, more saturated green with a glow, reserved for a night or target that's well above an ordinary good result:", swatches: [
                HelpSwatch(color: Palette.exceptional, label: "90 and above — Exceptional"),
                HelpSwatch(color: Palette.go, label: "75–89 — Excellent"),
                HelpSwatch(color: Palette.good, label: "60–74 — Good"),
                HelpSwatch(color: Palette.marginal, label: "45–59 — Marginal"),
                HelpSwatch(color: Palette.skip, label: "Below 45 — Poor")
            ]),
            HelpSection(heading: "Night Score vs. Target Score", body: "A night's score weighs clear dark time (35%), sky clarity (30%), the moon (25%), and conditions like wind and dew (10%). Clear dark time and sky clarity are both taken from the night's longest unbroken stretch of dark sky under your Maximum Cloud Cover — the \u{201c}Best imaging\u{201d} window shown at the top — measured against your Integration Goal. Nothing outside that stretch counts, good or bad: four clear hours make a night worth going out for however cloudy the rest of it is, while a whole night of scattered cloud that never gets under your limit scores poorly, since all it gives you is a lot of cloudy frames to throw away. A target's score weighs time on target (26%), sky darkness (18%), cloud cover (18%), how well it fills the frame (15%), how detectable it is against the sky background (14%), and altitude (9%). The two are calculated independently, on purpose — a night can be excellent overall while one particular target is a poor match for it, or the other way around.")
        ]),

        HelpTopic(title: "The Night Timeline", systemImage: "chart.bar.xaxis", sections: [
            HelpSection(body: "This chart is what the rest of the app is built around. Every target's availability bar beneath it shares the same time axis, so reading straight down any column tells you exactly what's visible at that moment."),
            HelpSection(heading: "What the Layers Mean", body: "", swatches: [
                HelpSwatch(color: Palette.astronomical, label: "Background — actual sky darkness, progressing from daylight blue through civil, nautical and astronomical twilight to black"),
                HelpSwatch(color: Palette.cloud, label: "Grey layer descending from the top — forecast cloud cover; the further it extends downward, the cloudier that hour is expected to be"),
                HelpSwatch(color: Palette.moonlight, label: "Pale wash over the background, together with the traced line near the bottom — moonlight and the moon's altitude throughout the night")
            ]),
            HelpSection(heading: "The Dotted Lines and the Red Line", body: "The two dotted vertical lines mark astronomical dusk and dawn — the boundary this app treats as genuine darkness. The thin red line marks the current time, when you're looking at tonight's plan."),
            HelpSection(heading: "Hovering", body: "Hold the pointer over any point on the chart for an exact readout: time, cloud percentage, temperature, how dark it is (as a percentage), and the moon\u{2019}s altitude, if it\u{2019}s above the horizon. With a target selected, its own altitude at that moment is shown too, in the accent colour \u{2014} and if it\u{2019}s up but still behind your blocked horizon in the direction it\u{2019}s currently in, the readout says so and names the direction, which is the difference between waiting an hour and giving up on it."),
            HelpSection(heading: "When a Target Is Selected", body: "Selecting a target from the list overlays its altitude curve, usable windows and single best window onto the sky and cloud layers, all in the app's one accent colour so a selection reads the same here as everywhere else. You can read the best window, and the reasoning behind it, off one chart without switching views.")
        ]),

        HelpTopic(title: "Sky View", systemImage: "globe", sections: [
            HelpSection(body: "Sky View is a classic planisphere: the zenith sits at the centre, the horizon forms the outer rim, and azimuth runs around the edge like a compass face — the N/E/S/W labels mark it. It's collapsed by default beneath the main timeline (look for the disclosure triangle) and shares that timeline's own scrubbed time, so dragging the slider at the bottom moves both views together."),
            HelpSection(heading: "What's Drawn on It", body: "The dome is the real night sky, turning with the time slider: the Milky Way, its dust lanes and the stars are all there, so there are no separate dots or bands to read. Twilight and moonlight are laid over it the way they are outside \u{2014} the sky brightens towards the Sun and the horizon at dusk and dawn, and a bright Moon lifts the whole sky and washes the Milky Way out first, leaving only the brighter stars. Only your selected target is marked, so the view is always about what you are about to point at.", swatches: [
                HelpSwatch(color: Palette.go, label: "The selected target \u{2014} green corner brackets with its name beneath, around your rig's true-size frame. The same green as the rig frame in the sky browser"),
                HelpSwatch(color: Palette.moonlight, label: "The Moon \u{2014} a plain disc, sized to its real apparent diameter for tonight's actual distance, only drawn while it's above the horizon"),
            ]),
            HelpSection(heading: "The Selected Target's Path", body: "Once a target is selected, its full day-long track is traced as a closed loop around the sky — a real fixed-coordinate target genuinely circles the pole once a day, and drawing the whole loop instead of stopping it at dusk and dawn is what makes that shape read as a real orbit rather than an arc that just happens to begin and end at nightfall. The portion above the horizon draws as a solid purple line; the rest of the loop, while it's below the horizon and out of reach, continues on as a faint one instead of vanishing, so the ring stays visibly whole. Wherever the above-horizon portion passes through a zenith-risk span (see below), it switches to amber instead of purple, the same amber used for warnings throughout the app. The target's brackets always sit on its own path, at whatever point corresponds to the current scrubbed time."),
            HelpSection(heading: "Zenith Risk, in Amber", body: "Alt-azimuth mounts — every current smart telescope — rotate the field fastest directly overhead, and some stall mechanically near the zenith altogether. \"Zenith Risk\" marks the real span of time a target spends above the zenith-avoidance altitude configured for the active rig in Settings → Equipment (default 80°, set to 90° to disable). It's the same underlying data behind the amber path here, the segmented time bar and warning triangle on a target's own detail page, and the warning triangle on ranked target rows and Tonight's Plan — one real time window, shown wherever a time window already appears, rather than a fact that only exists buried in a warning sentence. It's already irrelevant on an equatorial mount — none of this is ever computed for one — and \"Show zenith risk warnings\" in Settings → Equipment turns it off on an alt-az rig too, if it's just noise to you."),
            HelpSection(heading: "Rig and Roll", body: "Above the dome, a rig picker previews any preset or saved rig here without changing the active one used for scoring, and a roll slider turns the frame, since its on-sky orientation at imaging time isn\u{2019}t something the app can know on its own. The frame is only drawn when it clears the horizon entirely, and not at all within 2\u{b0} of the zenith, where this flat view can\u{2019}t draw it meaningfully; the brackets still mark the target either way. On an alt-az rig the frame visibly rotates as you scrub through the night \u{2014} that\u{2019}s real field rotation, the same effect behind Zenith Risk. On an equatorial rig it holds one orientation relative to the stars all night, same as the real mount does."),
            HelpSection(heading: "The Readouts Beneath the Scrubber", body: "As you drag the time slider, the line beneath it reports the selected target\u{2019}s live altitude and compass direction, and the line under that the rig\u{2019}s field and where the frame is pointing."),
            HelpSection(heading: "Playing Through the Night", body: "The round button beside the slider plays the whole chart window forward on its own, about 25 real seconds per evening, rather than dragging by hand. If Tonight's Plan has anything in it, two chips appear on the readout line to choose what playback does with the selection: \"Track Selected\" holds whatever's currently selected fixed while time advances, and \"Cycle Plan\" hands the selection off from one planned target to the next as playback crosses into each one's own scheduled window, so the detail pane on the right walks through the whole session with it. Which one is picked resets every time the selection itself changes: choosing something from tonight's plan — or nothing at all — defaults to Cycle Plan, while choosing anything else (browsing the full catalogue, say) switches to Track Selected automatically, since there'd be nothing of the plan left to hand off to otherwise. Either chip can still be tapped directly to override that default until the next selection change. Dragging the slider by hand always pauses playback rather than fighting it.")
        ]),

        HelpTopic(title: "Tonight's Plan", systemImage: "list.number", sections: [
            HelpSection(body: "This section on Home shows the night\u{2019}s plan at a glance: the app\u{2019}s own suggested session \u{2014} the highest-scoring non-overlapping targets that clear your minimum score, each given a contiguous block of time \u{2014} or your own manual plan once you have one. Home only shows it; you change it in the planner. Click a block or row to see that target in the Selected target panel."),
            HelpSection(heading: "One Target vs. Several", body: "When only one target clears the bar, it's shown as a single compact line — name, time window, duration — rather than the same target repeated as a timeline block, a plan row, and a ranked result underneath. The graphical Gantt-style strip only appears once there are two or more targets, since that's when relative order and overlap actually carry information worth a chart."),
            HelpSection(heading: "Zenith Risk Here Too", body: "A target whose planned window overlaps a zenith-risk span (see \"Sky View\") gets the same small amber warning triangle shown on ranked target rows, with a tooltip giving the time it starts."),
            HelpSection(heading: "Manual or Suggested", body: "The badge beside the section title says whose plan you are looking at. \u{201c}Suggested\u{201d} is the app\u{2019}s own, rebuilt whenever the forecast or your settings change. \u{201c}Manual\u{201d} means you have edited that night: it then stays exactly as you left it and nothing re-plans it. A night only becomes manual when you change its plan and press \u{201c}Done\u{201d}; opening the planner and closing it again leaves a suggestion a suggestion. \u{201c}Reset manual plan\u{201d} asks first, then removes your version and hands the night back to the app\u{2019}s current suggestion \u{2014} with an Undo until you next edit a plan. Plans are saved per night and survive quitting; nights that have already passed are dropped on the next launch, since this is a planner rather than a logbook."),
            HelpSection(heading: "The Planner", body: "\u{201c}Plan session\u{201d} on the night\u{2019}s summary, or \u{201c}Edit plan\u{201d} beside the plan, opens the planner in the main window. Across the top it keeps the night, its score, where you\u{2019}re observing from and which rig; below that is the session timeline you build on; underneath are the candidate targets on the left and the selected target on the right. Only the candidate list scrolls, so the timeline and the buttons never go out of reach. It starts from whatever the night already shows, since the scheduler usually has the shape of the night about right and the edits worth making are moving one block and splitting another."),
            HelpSection(heading: "Editing the Plan", body: "Drag a block along the night to move it; drag either end to change how long you spend there. The times, the length and any unshootable minutes show under the timeline while you drag. Click a block to select it, then use the arrow keys: \u{2190} and \u{2192} move it five minutes, Shift-arrows change its end, Option-arrows its start, \u{2191} and \u{2193} pick the neighbouring block, and Delete removes it. Every edit snaps to the nearest five minutes so times stay readable. Nothing is saved while you edit: the bar along the bottom says whether there are unsaved changes. \u{201c}Clear draft\u{201d} empties the plan; Esc puts the plan back the way it was when you opened the planner and keeps you there (it asks first); with nothing to undo it closes the planner. \u{201c}Cancel\u{201d} and \u{2190} Home close the planner, asking first if there are changes to lose. \u{201c}Done\u{201d} (\u{2318}\u{21a9}) saves your changes as this night\u{2019}s manual plan, which survives quitting the app; with no changes it just closes."),
            HelpSection(heading: "Choosing Candidates", body: "Search, type, sort and two constraints narrow the list: \u{201c}usable for at least\u{201d} a chosen time, and \u{201c}Fits my frame\u{201d}, which hides targets that overflow the frame or fill less than a tenth of it. \u{201c}Suggestion favours\u{201d} is the same setting as in Settings \u{2192} Planning; an untouched suggestion follows it straight away. Selecting a candidate only shows it on the right and its usable time under the timeline \u{2014} it never changes the plan. Rows already in the plan say Planned."),
            HelpSection(heading: "Pushing Blocks Around", body: "Drag a block into its neighbour and the neighbour shortens from the side being encroached on, the way dropping a clip onto a video timeline does. Keep pushing and it would eventually vanish, which is never what was meant \u{2014} so at the point it would drop below ten minutes it hops to the other side of the block you\u{2019}re dragging, at its full original length. That is how you reorder: push a block far enough into its neighbour and the two change places. Push far enough and a third block will get out of the way too, moving to the nearest gap that fits it. Dragging an *end* trims the same way but never makes anything swap \u{2014} that\u{2019}s a statement about how long you spend on this target, and a neighbour leaping across the night in response would be absurd. Blocks never overlap, because one telescope points at one thing at a time; when no arrangement works the block simply stops."),
            HelpSection(heading: "The Same Target More Than Once", body: "In the planner every candidate has an Add button, and the Selected target panel an \u{201c}Add to plan\u{201d} button, that drops a block for it into the longest gap left in the night, preferring time the target can actually be shot in. If every stretch the target could use is already taken, the block still goes in and the note under the timeline says why it\u{2019}s unshootable. Pressing it twice gives you two blocks of that target, which is the point: \u{201c}M31 for ninety minutes, NGC 1514 for two hours, then back to M31\u{201d} is a perfectly ordinary night, and a suggested plan can\u{2019}t express it because a suggestion holds each target at most once. \u{201c}Remove block\u{201d} under the timeline, or Delete, removes the selected block, not the target."),
            HelpSection(heading: "Longer Integration or More Targets", body: "Settings \u{2192} Planning chooses which way the suggested plan leans when the night is shorter than the targets that want it. \u{201c}Longer integration\u{201d} hands no target more than your full Integration Goal before the others get a turn, and won\u{2019}t suggest anything under a third of that at all \u{2014} a twenty-minute slot is gone by the time the mount has slewed and refocused, so offering one would contradict the setting. \u{201c}More targets\u{201d} halves the cap and drops that floor back to twenty minutes, so roughly twice as many fit and the short windows early in the night get used. Either way, time nobody else wants is still given back afterwards \u{2014} a night with one real target on it keeps the whole night. This only shapes what the app suggests: a plan you have edited by hand is yours, and changing this never rearranges it."),
            HelpSection(heading: "Clouded-Out Nights", body: "A night the forecast writes off entirely gets no plan at all \u{2014} there is nothing to schedule. The target list below still fills in, re-worked as though the cloud weren\u{2019}t there, so you can see what you\u{2019}d have had if it clears; a running order built from those would be a schedule for a night that isn\u{2019}t happening."),
            HelpSection(heading: "Hatched Blocks", body: "A block can be dragged anywhere, including to a time its target isn\u{2019}t up, isn\u{2019}t dark, or is forecast cloudy. That part of the block is drawn with diagonal hatching, the row underneath says how many minutes are affected, and the section header totals it across the whole plan. It\u{2019}s flagged rather than prevented on purpose \u{2014} a forecast is a forecast, and planning through a cloud band you don\u{2019}t believe in is your call to make. A block whose target has dropped out of tonight entirely is drawn in red and hatched end to end."),
        ]),

        HelpTopic(title: "Target Availability Bars", systemImage: "chart.xyaxis.line", sections: [
            HelpSection(body: "Each row in the target list has its own thin bar, sharing the night timeline's axis. Beneath it, a faint white line traces the target's altitude as it rises and sets — pure geometry, drawn even through hours when the target isn't usable."),
            HelpSection(heading: "What the Green Fill Means", body: "A segment fills, in the same colour as the target's score badge, only when all three hold at once: the target's above your minimum altitude, the sky's dark enough for your darkness threshold, and forecast cloud cover is under your maximum. A real three-way AND, checked every five minutes."),
            HelpSection(heading: "Why There Can Be Gaps", body: "Altitude rises then falls once a night, and once astronomical darkness starts it stays — neither one reverses partway through. Cloud cover isn't one-directional, though: if the forecast dips below the threshold, climbs back over it, then drops again, you'll see separate green segments with real gaps between them — not a rendering bug. The bright vertical tick marks that target's single best moment."),
            HelpSection(heading: "Example: Double Cluster", body: "If tonight's Double Cluster bar is one solid green block, it's above the horizon, the sky's dark, and the forecast stays clear the whole time. Two blocks with a gap between them mean the same thing, except a cloud patch is forecast in between — check the main timeline at that time and you'll see the grey cloud layer reaching further down."),
            HelpSection(heading: "The Line Beneath the Bar", body: "Beneath each availability bar sits one line of fixed-order figures — best time, peak altitude, percentage of the frame's long side filled, and total usable time — always in that order, so scanning straight down the list compares the same value in the same place on every row rather than parsing a differently-shaped sentence each time. A small amber warning triangle appears at the end of the line, with a tooltip on hover, whenever that target's best window passes through a zenith-risk span; see \"Sky View\" for what that means.")
        ]),

        HelpTopic(title: "\"In Your Frame\"", systemImage: "camera.viewfinder", sections: [
            HelpSection(body: "This panel, on each target's detail page, answers something a magnitude figure alone can't: will this actually produce a meaningful image through your specific telescope and sensor?"),
            HelpSection(heading: "Reading It", body: "The picture is real sky: a Digitized Sky Survey cutout centred on the target, at exactly your rig\u{2019}s field of view. The rectangle over it is your frame. Solid green means the target fits comfortably in a single frame. Dashed amber means it\u{2019}s oversized and would need a mosaic, or is being shown anyway because oversized targets are allowed in Settings. The number in the corner is your configured field of view in degrees, and the small cross marks the target\u{2019}s catalogued position \u{2014} the survey is shallow, so a faint target can be hard to make out. Its catalogued size, pixel scale and the photo credit are in the lines underneath."),
            HelpSection(heading: "Before the Picture Arrives", body: "The panel shows your frame over an empty sky and says it\u{2019}s fetching, then fills in when the cutout lands \u{2014} usually a second or two, and instantly for anything looked at before, since cutouts are cached on disk. If it can\u{2019}t be fetched at all, offline most likely, it says so rather than inventing something. Earlier versions drew a made-up star field with the catalogued size as an ellipse over it, which looked like a finished picture of something it wasn\u{2019}t, and disagreed with the real sky that replaced it a moment later."),
            HelpSection(heading: "Rig Presets", body: "The presets in Settings \u{2192} Equipment use published optical specs and the standard dimensions of each model\u{2019}s sensor. Check them against your own unit \u{2014} every number is editable, and a rig you save keeps your changes.")
        ]),

        HelpTopic(title: "Score Breakdown", systemImage: "list.bullet.rectangle", sections: [
            HelpSection(body: "The \"Why This Score\" section on each target's page lists every factor in its geometric mean, each with its own rating (Exceptional to Poor) and a bar scaled 0 to 100 percent. A line beneath each bar gives the real number behind it — actual usable minutes, actual surface brightness, and so on."),
            HelpSection(heading: "The \"−N\" Value Beside Each Factor", body: "This number is calculated, not estimated: set that one factor to its perfect value (1.0), recompute the geometric mean, and subtract the actual score. That's exactly how many points that factor is costing right now — not a fixed share of its weight, since in a geometric mean what one factor costs depends on all the others too. \"Main Limitation\" at the top is just whichever factor has the biggest −N."),
            HelpSection(heading: "\"Why Not Recommended\"", body: "Targets rated Marginal or Poor get a short list of real reasons, pulled from whichever factors are actually weakest — not a generic explanation."),
            HelpSection(heading: "In Your Frame", body: "The framing preview shows real sky, not a drawing: a cutout of the Digitized Sky Survey centred on the target, at exactly your rig\u{2019}s field of view, with the frame outline over it. Seeing the real thing is the point: a catalogued extent describes something far smaller than the part worth photographing for many objects \u{2014} an open cluster sitting inside a nebula is catalogued as the cluster, and the nebula is what you came for. Images are cached on disk, so a target you have looked at once works offline afterwards; until one arrives the panel shows your frame over an empty sky, and says so if it can\u{2019}t be fetched. DSS covers the whole sky, which is why it is used in preference to deeper surveys that leave gaps."),
            HelpSection(heading: "Detectability", body: "This measures surface brightness against the sky background, not just the raw catalogue magnitude. The target's light gets spread across its full catalogued size and compared to your Bortle-class sky background, adjusted for f-ratio, integration time and any filter in use — which is why the same galaxy can score well from a dark site and near zero from a city, on an otherwise identical clear night. It carries more weight than the other quality factors and is allowed to pull a score much further down, because it\u{2019}s the only one that can be fatal: an hour of cloud costs you part of a night, but a target fainter than the sky it sits on returns nothing at all, however long you leave the shutter open. When that\u{2019}s the case the target says so in its warnings, with the two brightness figures, rather than leaving you to infer it from a middling number."),
            HelpSection(heading: "Framing", body: "Full marks go to a target filling 30 to 80 percent of the frame\u{2019}s long side. A target too small for your rig to resolve \u{2014} under about 40 pixels across, which for a small smart telescope means anything under about a minute and a half of arc \u{2014} scores near zero here and lands in Poor however bright it is: there is no shape to record, only a fatter star. The same object scores properly at a focal length that does resolve it, since this is judged in pixels. Smaller under-uses the sensor; larger needs a mosaic, which costs a little if your rig supports mosaicking and a lot if it doesn't.")
        ]),

        HelpTopic(title: "Cloud, Moon & Weather Numbers", systemImage: "cloud.moon", sections: [
            HelpSection(heading: "Cloud Percentage", body: "Every cloud percentage you see — sidebar, night header, hover readout — is an effective figure, not the raw forecast. Open-Meteo splits cloud cover into low, mid and high layers; low cloud counts at full strength here, mid-level at 85 percent, and thin high cirrus at only 50 percent, since cirrus barely touches an image while low cloud wrecks it. Your \"Maximum Cloud Cover\" setting is checked against this effective figure, not the raw one."),
            HelpSection(heading: "Moon", body: "A bright moon doesn't shorten the night — darkness windows come from the sun alone — it's applied instead as a per-target quality penalty. That penalty scales with lunar phase raised to the power of 2.2 (a half moon is a lot less than half as bright as a full one), with the moon's own altitude, and with the target's angular separation from it. A dual-band filter cuts this penalty to 40 percent and adds contrast for emission nebulae, planetary nebulae and supernova remnants — which is why the app might recommend the Crescent Nebula under a gibbous moon while steering you away from a galaxy the same night."),
            HelpSection(heading: "Seeing", body: "Seeing is estimated from surface wind gusts. Real seeing depends on jet stream conditions, which no free forecast exposes — treat this as a hint, not a measurement."),
            HelpSection(heading: "Estimated Dew Risk", body: "Dew risk is rated from the forecast spread between air temperature and dew point: more than 10°F is Low, 6–10°F Moderate, 3–6°F High, and 3°F or less Very High. It doesn't wait for the spread to reach zero, because a telescope under a clear sky radiates heat away and cools below the air around it — its optics can dew over while the reported temperature is still several degrees above the dew point. So when the sky is mostly clear and the wind is under about 5 mph, the rating goes up one step. Cloud (which sends heat back down) or a breeze (which keeps the tube at air temperature) withholds that step, but never lowers a Very High spread. The rating shown is the worst hour of your session — Tonight's Plan from its first block to its last, or astronomical darkness without a plan — with the tightest spread and when it comes, and the bar under the night chart shows how it changes through the night. It's an estimate from the forecast, not a prediction that dew will or won't form.", swatches: [
                HelpSwatch(color: Palette.dewRisk(.low), label: "Low — dew heater probably unnecessary"),
                HelpSwatch(color: Palette.dewRisk(.moderate), label: "Moderate — monitor optics; dew protection may be useful"),
                HelpSwatch(color: Palette.dewRisk(.high), label: "High — dew heater recommended"),
                HelpSwatch(color: Palette.dewRisk(.veryHigh), label: "Very High — dew heater recommended")
            ])
        ]),

        HelpTopic(title: "Bortle Class & Your Site", systemImage: "mappin.and.ellipse", sections: [
            HelpSection(body: "Bortle class — 1 (pristine) to 9 (inner-city) — matters more than almost anything else in the app. You enter it by hand in Settings → Location, since no free API can actually measure your sky. It sets the zenith sky brightness behind every detectability calculation, which is why the same galaxy can be a non-starter from a Bortle 8 backyard and an easy target from a Bortle 4 site twenty miles away. If you don\u{2019}t know yours, look your site up on a light pollution map."),
            HelpSection(heading: "Blocked Horizon", body: "The altitude below which trees, buildings or terrain block your actual view. Anything that never climbs above it is treated as unobservable, no matter what the raw ephemeris says. The slider in Settings sets every direction at once, which is the right answer for most sites; open \u{201c}One direction is worse\u{201d} underneath it if something in particular \u{2014} one big tree, a neighbour\u{2019}s roof \u{2014} takes out part of your sky and the rest of it is fine."),
            HelpSection(heading: "One Direction Is Worse", body: "Eight sliders, one per compass point, each covering the 45\u{b0} of sky centred on it \u{2014} so S also covers SSE through SSW. A target is only ignored while it\u{2019}s below the line for the direction it\u{2019}s actually in, so something that spends the first half of the night behind the tree to the south and the rest of it clear to the west keeps the half you could really shoot. When that costs a target half an hour or more of otherwise good sky, it says so in that target\u{2019}s warnings, naming the direction. Sky View draws it too: the blocked sector steps inward, so the bite out of the dome is the shape of your actual sky. Dragging the main Blocked Horizon slider levels all eight again."),
            HelpSection(heading: "Saving More Than One Spot", body: "A front yard and a back yard are the same coordinates, the same forecast and the same Bortle class, and differ only in what is in the way \u{2014} so \u{201c}Save as a separate spot\u{201d} in Settings copies the current site under its own name, leaving you to set that copy\u{2019}s horizon. The copy becomes the site in use straight away, since describing it is the next thing you want to do. Saved sites list their horizon underneath the coordinates, which is the only line that tells two spots at one address apart. Searching for a place you have already saved keeps the name and horizon you gave it rather than resetting them, and if you have several saved at one address it keeps you on the one already in use."),
            HelpSection(heading: "Better Spot Nearby", body: "The section under the night list looks for a real place — a park, campground, beach, marina or boat ramp — within the distance you pick that's better to observe from than your site. The menu beside its title picks what \"better\" means: Darker sky or Open horizon. It never sends you further than you need to go: if somewhere closer is nearly as good as the best spot in range — within about a third of a magnitude, or 3° of horizon — it suggests the closer one, whichever distance you've picked. Anything listed underneath is closer still, just not as good."),
            HelpSection(heading: "Park Hours", body: "Most parks close at dusk, so check before you drive out. Where a park's hours are actually on record, the spot shows them — green if it stays open long enough after dark to be worth it tonight, amber if it closes at sunset or soon after dark. Where they aren't, there's a Check hours link to the park's website when one's known. Apple Maps doesn't share opening hours with apps, so hours come from OpenStreetMap (© OpenStreetMap contributors), which has them for only a minority of parks — no label means unknown, not open. Astronomy clubs often have arrangements to stay after hours at particular parks; it's worth asking one near you."),
            HelpSection(heading: "Darker Sky", body: "Looks for somewhere the sky should be noticeably darker than at your site. Bortle classes here, yours and each spot\u{2019}s, are estimated from NASA satellite measurements of night lights. It shows the place's estimated Bortle class next to the same estimate for your site, and how many targets would score Good or better from there tonight compared with from here. Use This Spot switches planning to it and saves it next to your current site; Back to… switches home again. If the Bortle class you set for your site is two or more classes off the satellite estimate, the panel says so and offers to update it — the comparison is only as fair as that setting. It assumes the same blocked horizon as your site — if the spot is more open, lower it in Settings. And it can't know whether a park is open or safe after dark, so check before you go."),
            HelpSection(heading: "Open Horizon", body: "For when the sky's dark enough but trees or rooftops are in the way. Within a mile or few, it finds the most open ground in each nearby park or boat ramp from satellite land cover, and shows how low the horizon is there next to your own Blocked Horizon setting, which direction is clearest, and how much more of the sky you'd see. The Map link goes to that open patch itself, not the park's entrance. Use This Spot saves the spot with its estimated horizon. The satellite data knows where trees are but not how tall they are, so it assumes about 15 m — taller pines will block a few degrees more.")
        ]),

        HelpTopic(title: "Planning Settings", systemImage: "slider.horizontal.3", sections: [
            HelpSection(body: "These, in Settings → Planning, decide what counts as usable and what gets shown. They don't change any underlying astronomical calculation — just the thresholds applied to it."),
            HelpSection(heading: "Maximum Cloud Cover", body: "What you count as clear. Hours with effective cloud cover above this get excluded — it's the number the green availability bars are tested against, and it decides the night's longest clear stretch, which the night score is built on. Around 20% separates a night with a genuinely clear window from one of steady scattered cloud."),
            HelpSection(heading: "Minimum Darkness", body: "How far below the horizon the sun has to be before an hour counts as dark. Shown as a slider from twilight to fully astronomically dark, rather than raw degrees."),
            HelpSection(heading: "Minimum Altitude", body: "Targets below this altitude are excluded, on top of your blocked-horizon limits — useful for ruling out the murky, high-airmass sky near the horizon even where nothing's physically in the way."),
            HelpSection(heading: "Integration Goal", body: "The usable minutes a target needs to earn full marks on \"Time on Target.\" Set it to the session length you actually plan to shoot."),
            HelpSection(heading: "Hide Below Score", body: "A display filter on the target list only. Lowering it reveals more marginal targets without changing how anything is scored."),
            HelpSection(heading: "UI Scale", body: "Under the night list. With Auto on, the whole interface sizes itself to the window: a comfortable size for its width \u{2014} about 120% filling a laptop screen, nearer 145% filling a 4K one \u{2014} or smaller if that\u{2019}s what it takes for the night rows, Tonight\u{2019}s Plan and the target list to stay on one line with nothing cut off. It re-fits whenever the window changes size. The night\u{2019}s statistics and the chart key wrap whole items onto a second row rather than shrinking everything to fit on one. Turn Auto off to set the size yourself with the slider, which starts from wherever Auto had got to."),
            HelpSection(heading: "Nights Ahead", body: "How many nights the list plans. Open-Meteo forecasts further out than the maximum, but cloud cover past about a week is not worth acting on.")
        ]),

        HelpTopic(title: "Data Sources & Accuracy", systemImage: "antenna.radiowaves.left.and.right", sections: [
            HelpSection(body: "Everything this app shows comes from one of three places: a live weather forecast, astronomy computed locally on your Mac, or a catalogue built into the app itself. None of it is guessed."),
            HelpSection(heading: "Weather", body: "Cloud cover (split into low, mid and high layers), dew point, humidity, wind and gusts all come from Open-Meteo — a free forecast API that needs no account and no API key. Across the US and southern Canada the numbers are NOAA\u{2019}s National Blend of Models, the weighted, bias-corrected blend of every major model that the National Weather Service\u{2019}s own forecast starts from, rather than a single model that can be the odd one out on a night the models disagree. The Blend gives total cloud but no layers, so each hour\u{2019}s low/mid/high mix is taken from Open-Meteo\u{2019}s regular forecast and scaled to the Blend\u{2019}s total. Outside its area, and past its range of about 11 days, the regular forecast is used on its own. One request is made per location each time you refresh; the age of the data currently in use is shown in the sidebar footer. If Open-Meteo can't be reached, the app quietly falls back to MET Norway (also free, also keyless), and the footer says \"backup source\" so a lower-fidelity forecast is never mistaken for the primary one — MET Norway doesn't publish wind gusts or a precipitation probability outside the Nordics, so those two figures become estimates in that case. To avoid hammering either service, automatic refreshes (app launch, changing a setting) are limited to once an hour; the Refresh button and Cmd-R always fetch immediately regardless."),
            HelpSection(heading: "Place Search", body: "Typing a place name in Settings → Location searches Open-Meteo's own geocoding endpoint, the same service as the weather, under the same terms. Typed coordinates skip this entirely."),
            HelpSection(heading: "Sky Overhead Panel", body: "The satellite image in the sidebar, under the night list, comes from NASA's GIBS Worldview service — free, no account, no API key. It's GOES-East's GeoColor product: true-colour by day, infrared cloud texture and city lights by night, so it stays readable after dark rather than going blank. It's refreshed alongside the weather, on the same once-an-hour throttle. GOES-East only sees the Americas, so outside that footprint the panel simply doesn't appear."),
            HelpSection(heading: "Better Spot Nearby: Open Horizon", body: "Trees, buildings, grass and water come from ESA WorldCover 2021, a 10 m global land-cover map made from Copernicus Sentinel-1 and Sentinel-2 satellite imagery (© ESA WorldCover project 2021 / Contains modified Copernicus Sentinel data (2021) processed by ESA WorldCover consortium; CC BY 4.0). It's read directly from the dataset's free public copy, downloading only the small pieces around your site. From each candidate standing point, sight lines run out 600 m in 36 directions; the tallest obstruction along each sets how high the sky is blocked that way. Land cover doesn't record height, so trees count as 15 m, mangroves 6 m, buildings and paving 4 m and shrubs 2 m. The horizon shown is the altitude that clears three quarters of all directions."),
            HelpSection(heading: "Better Spot Nearby: Darker Sky", body: "Light pollution comes from NASA's Black Marble nightly radiance — satellite measurements of light shining up from the ground, with moonlight already removed — fetched from the same free GIBS service as the Sky Overhead panel. Six dates across the past year are combined to smooth out cloud gaps, then kept for 60 days. Sky glow at each candidate spot adds up every light within about 140 km, fading with distance to the power of 2.5 (Walker's law). One scale factor turns that into sky brightness; it was fitted once against a published light-pollution atlas at 18 places around Tampa, Denver and Anchorage, where the model agreed to within about a fifth of a magnitude. Treat the Bortle numbers as good to roughly half a class — much better at telling you which of two nearby places is darker than at naming either one exactly. Places themselves come from Apple Maps search, which needs no account or key."),
            HelpSection(heading: "Astronomy", body: "Every Sun and Moon position, every rise, set and twilight time, the Milky Way's position, and every target's altitude and azimuth is computed right on your Mac — no network request involved. The Sun uses the standard low-precision Meeus series, accurate to about 0.01°; the Moon uses a truncated ELP series, accurate to a few arcminutes in position and roughly a quarter hour in phase timing. Rise, set and twilight times are found by sampling altitude on a fixed grid and refining the crossing by bisection, which is also why circumpolar targets and polar summers work without any special-case logic."),
            HelpSection(heading: "The Catalogue", body: "The built-in target list is the complete Messier catalogue, 49 more non-Messier showpieces, and roughly 1,000 further NGC/IC objects — about 1,150 in total — compiled directly into the app rather than fetched from anywhere. Positions are J2000, quoted to about an arcminute."),
            HelpSection(heading: "OpenNGC", body: "The ~1,000 objects beyond Messier and the hand-picked showpieces come from OpenNGC (github.com/mattiaverga/OpenNGC), a maintained, openly licensed (CC-BY-SA-4.0) database of every NGC and IC object. They were selected by real brightness — not typed in from memory — with a script, kept in the app's own repository, that can be re-run if the upstream data ever improves."),
            HelpSection(heading: "Custom Targets", body: "Anything still missing can be added by hand from the Target Catalog window's + button — designation, type, position and size. A custom target is scored and planned exactly like a built-in one, and shows a small \"Custom\" badge in the catalog grid so it's easy to tell apart. Tap it again to edit or delete it."),
            HelpSection(heading: "Target Photographs", body: "Where a target's detail page or catalogue entry shows a photograph, it was pulled from Wikipedia at build time — Wikipedia only hosts appropriately licensed media, and the link beneath each photo credits the exact source article for full attribution and licence detail. Not every target has one."),
            HelpSection(heading: "The Moon", body: "The Moon drawn when you click it in a night\u{2019}s header is NASA\u{2019}s Scientific Visualization Studio CGI Moon Kit colour map, made from Lunar Reconnaissance Orbiter Camera data, wrapped onto a sphere and lit from the Sun\u{2019}s direction at the moment the Moon stands highest that night, turned the way it appears from your site. Libration and the small tilt of the Moon\u{2019}s axis are left out."),
            HelpSection(heading: "The Sky View's Star Map", body: "The sky in Sky View is NASA\u{2019}s Deep Star Maps 2020 from the Goddard Scientific Visualization Studio (svs.gsfc.nasa.gov/4851), rendered from the positions, brightnesses and colours of 1.7 billion stars in the Gaia DR2 (ESA/Gaia/DPAC), Hipparcos-2 and Tycho-2 catalogues. It ships inside the app, so the dome works offline. Twilight and moonlight over it are modelled on your Mac from the Sun and Moon positions above \u{2014} an impression of how bright the sky is, not a photometric prediction.")
        ])
    ]
}

struct HelpView: View {
    @State private var selection: String? = HelpContent.topics.first?.id

    var body: some View {
        NavigationSplitView {
            List(HelpContent.topics, selection: $selection) { topic in
                Label(topic.title, systemImage: topic.systemImage)
                    .tag(topic.id)
            }
            .listStyle(.sidebar)
            .scrollContentBackground(.hidden)
            .background(Palette.spaceBackground)
            .navigationSplitViewColumnWidth(min: 200, ideal: 230, max: 280)
        } detail: {
            if let topic = HelpContent.topics.first(where: { $0.id == selection }) {
                HelpTopicView(topic: topic)
            } else {
                EmptyStateView(title: "Select a Topic",
                               message: "Choose an item from the list at left to view its explanation.",
                               systemImage: "questionmark.circle")
            }
        }
        .navigationTitle("Sky Bother User Guide")
        .frame(minWidth: 760, minHeight: 640)
    }
}

private struct HelpTopicView: View {
    @Environment(\.uiTextScale) private var uiTextScale
    var topic: HelpTopic

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 20) {
                HStack(spacing: 10) {
                    Image(systemName: topic.systemImage)
                        .font(.scaled(.title, scale: uiTextScale).weight(.semibold))
                        .foregroundStyle(Palette.accent)
                    Text(topic.title)
                        .font(.scaled(.title, scale: uiTextScale).weight(.semibold))
                }

                ForEach(topic.sections) { section in
                    VStack(alignment: .leading, spacing: 8) {
                        if let heading = section.heading {
                            Text(heading)
                                .font(.scaled(.title3, scale: uiTextScale).weight(.semibold))
                        }
                        if !section.body.isEmpty {
                            Text(section.body)
                                .font(.scaled(.body, scale: uiTextScale))
                                .foregroundStyle(.secondary)
                                .fixedSize(horizontal: false, vertical: true)
                        }
                        if !section.swatches.isEmpty {
                            VStack(alignment: .leading, spacing: 7) {
                                ForEach(section.swatches) { swatch in
                                    HStack(alignment: .top, spacing: 9) {
                                        RoundedRectangle(cornerRadius: 3)
                                            .fill(swatch.color)
                                            .frame(width: 18, height: 14)
                                            .overlay(RoundedRectangle(cornerRadius: 3).strokeBorder(Color.primary.opacity(0.2)))
                                            .padding(.top, 2)
                                        Text(swatch.label)
                                            .font(.scaled(.callout, scale: uiTextScale))
                                            .foregroundStyle(.secondary)
                                            .fixedSize(horizontal: false, vertical: true)
                                    }
                                }
                            }
                            .padding(.top, 2)
                        }
                    }
                    .padding(14)
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .panelStyle()
                }
            }
            .padding(28)
            .frame(maxWidth: 640, alignment: .leading)
            .frame(maxWidth: .infinity)
        }
        .spaceBackground()
        .navigationTitle(topic.title)
    }
}
